---

- hosts: updatableServers

  tasks:

    - name: 'install sophos antivirus'
      include_role:
        name: sophos_install
      when:
        - sophos_av.url is defined
        - sophos_av.url | length > 0
...
