---
- hosts: achievo
  become: true
  tasks:
    - name: Get db password
      shell: echo -n $(grep config_db {{ achievo.home|default('/var/www/html/achievo') }}/config.db.php | grep password | awk '{print $NF}' | awk -F'\"' '{print $2}')| sha256sum | awk '{print $1}'
      register: output

    # Beware the correct quoting!
    - name: Create user in achievo
      command: php {{ achievo.home|default('/var/www/html/achievo') }}/api.inc.php '{{ hostvars.get("localhost").get("user")|to_json }}' "{{ output.stdout }}"
      register: achievo

    - debug: var=achievo.stdout

    - uri:
        url: "{{ ticket_system }}/rest/api/2/issue/{{ hostvars.get('localhost').get('ticket_number') }}/comment"
        user: "{{ ticket_user }}"
        password: "{{ ticket_password }}"
        method: "POST"
        force_basic_auth: yes
        status_code: [201]
        body_format: "json"
        body:
          body: "Achievo Account angelegt"
