#!/usr/bin/env ansible-playbook
---

###
## Licenced under CC-BY
##
## MAIN FILE to create a new USER ACCOUNT in ITE systems
###

- name: Fetch data from ticket system
  import_playbook: gather_data.yml
  tags:
    - ssl
    - achievo
    - mail
    - welcomemail
    - ldap
    - success

- name: Confirmation
  hosts: localhost
  tasks:
    - name: skip if nothing to do
      meta: end_play
    - pause: prompt="Create user __ {{ hostvars['localhost']['user']['registration']['user']['username'] }} __ in environment __ {{ env }} __ and system __ {{ hostvars.get('localhost').get('ldap_url') }} __, press ENTER to continue (abort with ctrl+c)."
      when: env == 'production' and (run_unattended is not defined or not run_unattended | bool)
  tags:
    - ssl
    - achievo
    - mail
    - welcomemail
    - ldap
    - success

- name: Check SSL Cert
  include: check_cert.yml
  when: hostvars['localhost']['ticket_number'] != -1
  tags:
    - ssl

- name: Check achievo
  include: check_achievo.yml
  when: skipAchievo is not defined and hostvars['localhost']['ticket_number'] != -1
  tags:
    - achievo

- name: Create ldap account
  include: ldap.yml
  when: hostvars['localhost']['ticket_number'] != -1
  tags:
    - ldap

- name: Create achievo account
  import_playbook: achievo.yml
  tags:
    - achievo
  when: skipAchievo is not defined and hostvars['localhost']['ticket_number'] != -1

- name: Generate SSL certificate
  import_playbook: ssl.yml
  when: hostvars['localhost']['ticket_number'] != -1
  tags:
    - ssl

- name: Upload certificate to LDAP
  import_playbook: ssl_ldap.yml
  when: hostvars['localhost']['ticket_number'] != -1
  tags:
    - ssl

- name: Upload SSL certificate
  import_playbook: ssl_upload.yml
  when: hostvars['localhost']['ticket_number'] != -1
  tags:
    - ssl

- name: Cleanup temp files
  import_playbook: cleanup.yml
  when: hostvars['localhost']['ticket_number'] != -1
  tags:
    - ssl

- name: Send welcome mail
  import_playbook: welcomemail.yml
  when: hostvars['localhost']['ticket_number'] != -1
  tags:
    - welcomemail
