---
- hosts: pki
  become: true
  vars:
    noSSL:
      - "12700"
      - "11403"
      - "11402"

  tasks:
    - set_fact:
        user: "{{ hostvars.get('localhost').get('user') }}"

    - debug:
        msg: "Creating user certificate {{ user.registration.user.username }} with employer {{ user.registration.contract.employer }} id {{ user.registration.contract.employerId }}"
      when: user.registration.contract.employerId not in noSSL


    - block:
      - set_fact:
          status: "{% if user.registration.user.lvl == 'Freelancer'%}external{% else %}internal{% endif %}"

      # TODO check in index.txt instead?
      - name: Check if already created
        stat:
          path: "/home/sysadmin/Private/it-economics_CA/{{ status }}/{{ user.registration.user.mail }}"
        register: keydir

      - block:
        - name: Copy generation script
          copy:
            src: ../files/generate
            dest: /tmp/generate
            mode: 0755

        - name: Generate SSL certificate
          shell: /tmp/generate {{ status }} {{ user.registration.user.mail }}  "{{ user.registration.user.firstname }} {{ user.registration.user.name }}" {{ ca_password }} {{ p12_password }}

        - name: Delete generation script
          file:
            path: /tmp/generate
            state: absent
        when: not keydir.stat.exists

      - name: Fetch files from pki
        fetch: src=/home/sysadmin/Private/it-economics_CA/{{ status }}/{{ user.registration.user.mail }}/it-economics_{{ user.registration.user.mail }}.{{ item }} dest=/tmp/it-economics_{{ user.registration.user.mail }}.{{ item }} flat=yes
        with_items:
          - p12
          - cer
          - crt
      when: user.registration.contract.employerId not in noSSL

    - uri:
        url: "{{ ticket_system }}/rest/api/2/issue/{{ hostvars.get('localhost').get('ticket_number') }}/comment"
        user: "{{ ticket_user }}"
        password: "{{ ticket_password }}"
        method: "POST"
        force_basic_auth: yes
        status_code: [201]
        body_format: "json"
        body:
          body: "Zertifikat erstellt"
      when: user.registration.contract.employerId not in noSSL
