- hosts: localhost
  become: false
  vars:
    noSSL:
      - "12700"
      - "11403"
      - "11402"
  tasks:
    # Deploy CRT to LDAP
    - block:
      - name: Get contents of pem file and remove header and footer
        shell: awk '/-----BEGIN CERTIFICATE-----/{flag=1;next}/-----END CERTIFICATE-----/{flag=0}flag' /tmp/it-economics_{{ user.registration.user.mail }}.crt | sed -e 's/^/ /'
        register: certificate

      - name: Setting Facts for Cert
        set_fact:
          certificate: "{{ certificate.stdout }}"

      - name: Send upload cert for user request to directory
        uri:
          method: POST
          return_content: yes
          headers: {"Authorization": "Basic {{ hostvars.get('localhost').get('auth_b64') }}" }
          url: "{{ hostvars.get('localhost').get('directory_url') }}{{ hostvars.get('localhost').get('directory_url_upload_user_cert') }}?api_token={{ hostvars.get('localhost').get('admin_api_token') }}"
          body_format: json
          body:
           data: "{{ certificate }}"
           uid: "{{ user.registration.user.username}}"
        register: response
        failed_when: "'false' in response.json['Object Status'] or 'json' not in response"
      when: user.registration.contract.employerId not in noSSL

    - uri:
        url: "{{ ticket_system }}/rest/api/2/issue/{{ hostvars.get('localhost').get('ticket_number') }}/comment"
        user: "{{ ticket_user }}"
        password: "{{ ticket_password }}"
        method: "POST"
        force_basic_auth: yes
        status_code: [201]
        body_format: "json"
        body:
          body: "Zertifikat in ldap-certs bereitgestellt"
      when: user.registration.contract.employerId not in noSSL
