---

- name: 'add mysql to `additionalcontainers` variable'
  set_fact:
    mysql_cnt: "{{ mysql_cnt | combine { 'name' : stack.name + '_' + mysql_cnt.name } }}"
    additionalcontainers: "{{ additionalcontainers | combine ( [ mysql_cnt ] ) }}"

- name: 'prepare configuration path'
  set_fact:
    mysql_templates:
      - "mysqld.cnf"
    mysql_path: "mysql/config"
    mysql_full_path: "{{ template_destination }}/{{ stack.name }}/{{ mysql_path }}/"

- name: Create needed dirs – if they do not already exist
  file:
    path: "{{ mysql_full_path }}"
    state: directory
    mode: "0755"

- name: 'Ensure MySQL configs are installed'
  template:
    src: "{{ item }}.j2"
    dest: "{{ mysql_full_path }}{{ item|basename }}"
  with_items: "{{ mysql_templates }}"

- name: 'add template information for further handling'
  set_fact:
    templates_to_be_moved: "{{ templates_to_be_moved | combine ( {
        'destination': mysql_path,
        'template': template_destination + '/' + stack.name + '/' + mysql_path + '/' + {{ item/basename }},
    } ) }}"
  with_items: "{{ mysql_templates }}"

...
