---

applications:

  wireguard-stack:
    wireguard:
      name: wireguard
      image: "{{ docker_registry }}linuxserver/wireguard"
      restartPolicy: always
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      environment:
        PUID: "1000"
        PGID: "1000"
        TZ: "Europe/London"
        SERVERURL: "hq1-muc.it-economics.de" #optional
        SERVERPORT: "51820" #optional
        PEERS: "70" #optional
        PEERDNS: "auto" #optional
        INTERNAL_SUBNET: "10.13.13.0" #optional
        ALLOWEDIPS: "0.0.0.0/0" #optional
      volumes:
        - "/var/wireguard/config:/config"
        - "/lib/modules:/lib/modules"
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
      labels:
        - "traefik.enable: 'false'"
      networks:
        - "backbone"
      ports:
        - 51820:51820/udp

  openvpn-stack:
    openvpn:
      name: openvpn
      privileged: true
      image: "{{ docker_registry }}iteconomics/openvpn:latest"
      restartPolicy: always
      volumes:
        - '/srv/openvpn/config/ite.conf:/etc/openvpn/ite.conf'
        - '/srv/openvpn/config/ldap.cfg:/etc/openvpn/ldap.cfg'
        - '/srv/openvpn/ssl:/etc/ssl/vpn'
      labels:
        - "traefik.enable: 'false'"
      networks:
        - "backbone"
      ports:
        - 6443:443

  devopenvpn-stack:
    devopenvpn:
      name: devopenvpn
      privileged: true
      image: "{{ docker_registry }}iteconomics/openvpn:latest"
      restartPolicy: always
      volumes:
        - '/srv/openvpn/config/devops.conf:/etc/openvpn/ite.conf'
        - '/srv/openvpn/config/ldap.cfg:/etc/openvpn/ldap.cfg'
        - '/srv/openvpn/ssl:/etc/ssl/vpn'
      labels:
        - "traefik.enable: 'false'"
      networks:
        - "backbone"
      ports:
        - 8443:443


  openvpn-testing-stack:
    openvpn-testing:
      name: openvpn-testing
      privileged: true
      image: "{{ docker_registry }}iteconomics/openvpn:testing"
      restartPolicy: always
      volumes:
        - '/srv/openvpn/config/devops.conf:/etc/openvpn/ite.conf'
        - '/srv/openvpn/config/ldap.cfg:/etc/openvpn/ldap.cfg'
        - '/srv/openvpn/ssl:/etc/ssl/vpn'
      labels:
        - "traefik.enable: 'false'"
      networks:
        - "backbone"
      ports:
        - 8444:443

  portainer_agent_stack:
    portainer_agent:
      name: portainer_edge_agent
      image: "{{ docker_registry }}portainer/agent"
      restartPolicy: always
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/var/lib/docker/volumes:/var/lib/docker/volumes"
#        - "/:/host"
        - "/var/portainer_agent/data:/data"
      labels:
        - "traefik.enable: 'false'"
      environment:
        EDGE: 1
        EDGE_ID: ffa38b27-d464-4cd9-a6f0-fc22979ce9d5
        EDGE_KEY: aHR0cDovL25sYi5pdC1lY29ub21pY3MuZGU6OTAwMHxubGIuaXQtZWNvbm9taWNzLmRlOjgwMDB8ZDc6MDE6Mjk6ODc6NjM6NjQ6MDc6Zjg6YmM6OGI6Yjc6Y2E6NjU6NGY6Yzk6NDF8OA
        CAP_HOST_MANAGEMENT: 1
      networks:
        - "database"

  guacamole_stack:
    guacamole:
      name: guacamole
      image: "{{ docker_registry }}oznu/guacamole:latest"
      restartPolicy: always
      volumes:
        - "{{ docker_home }}/guacamole/postgres:/config"
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.guacamole.loadbalancer.server.port: '8080'"
        - "traefik.http.routers.guacamole_http.rule: 'Host(`jump2.it-economics.de`)'"
        - "traefik.http.routers.guacamole_http.entrypoints: 'web'"
        - "traefik.http.routers.guacamole_http.middlewares: 'forcehttps@file'"
        - "traefik.http.routers.guacamole.rule: 'Host(`jump2.it-economics.de`)'"
        - "traefik.http.routers.guacamole.entrypoints: 'websecure'"
        - "traefik.http.routers.guacamole.tls: 'true'"
        - "traefik.http.routers.guacamole.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.guacamole.tls.domains[0].main: 'it-economics.de'"
        - "traefik.http.routers.guacamole.tls.domains[0].sans: '*.it-economics.de'"
      networks:
        - "backbone"
      environment:
        EXTENSIONS: "auth-quickconnect,auth-totp"


...
