---

- name: Ensure pip and nfs-common are installed
  apt:
    name: ['python3-pip', 'nfs-common', 'jq']
    state: present
    update_cache: yes

- name: Ensure pip packages are up to date
  pip:
    name: pip
    state: latest

- name: Install j2cli
  pip:
    name: j2cli 
    state: latest
    extra_args: "--ignore-installed"

- name: Ensure required scripts are installed
  copy:
    src: launch-config-functions.sh
    dest: /usr/bin/launch-config-functions.sh
    mode: 0755
    owner: root
    group: root
  
- name: Ensure required scripts are installed
  template:
    src: launch-config.sh.j2
    dest: /usr/bin/launch-config.sh
    mode: 0755
    owner: root
    group: root

- name: Ensure required templates are copied
  copy:
    src: "{{ item }}"
    dest: "/home/ubuntu/{{ item }}" 
    mode: 0777
    owner: ubuntu 
    group: ubuntu
  with_items:
    - confluence.cfg.xml.j2
    - jira_dbconfig.xml.j2

- name: Ensure service script is installed
  copy:
    src: autostart
    dest: /etc/init.d/atlassian-application
    mode: 755
    owner: root
    group: root

- name: Ensure dependencies are installed
  apt:
    name: xmlstarlet
    update_cache: true
    state: present

- name: Ensure service is enabled
  service:
    name: atlassian-application
    enabled: yes

...