- name: Ensure awslogs-agent setup script is installed
  get_url: url=https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb dest=/var/tmp/amazon-cloudwatch-agent.deb
  
- name: Ensure main config is installed
  template: src=config.j2 dest=/home/root/.aws/config owner=root group=root
  register: main

- name: Ensure agent is installed
  command: dpkg -i -E /var/tmp/amazon-cloudwatch-agent.deb

- name: Ensure application config is installed
  template: src=amazon-cloudwatch-agent.json.j2 dest=/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json owner=root group=root

- name: Restart service when config changed
  service: name=amazon-cloudwatch-agent state=restarted

- name: Cleanup
  file: path={{ item }} state=absent
  with_items:
    - /var/tmp/amazon-cloudwatch-agent.deb

  # Service cannot be disabled since it will be automatically started by awslogs-nanny-sh crontab entry if it is not running (executed every minute)
