---
- debug:
    msg: "{{ app }}"

- name: "Ensures {{ composerFilePath }}/{{ app.key }} dir exists"
  file: 
    path: "{{ composerFilePath }}/{{ app.key }}"
    state: directory
    recurse: yes
  when: remote == true 

- name: Provision docker-compose
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ composerFilePath }}/{{ app.key }}/docker-compose.yml"
  when: remote == true  

- name: "Ensures {{ composerFilePath }}/{{ app.key }} dir exists"
  file:
    path: "{{ composerFilePath }}/{{ app.key }}"
    state: directory
    recurse: yes
  delegate_to: localhost
  when: remote != true

- name: Provision docker-compose
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ composerFilePath }}/{{ app.key }}/docker-compose.yml"
  delegate_to: localhost
  when: remote != true
...
