---

loglevel:     "ERROR"
insecureOnly: no

tlsChallenge: no
### configure along documentation https://docs.traefik.io/https/acme/#dnschallenge
### https://go-acme.github.io/lego/dns/
###
### e.g.:
# dns_provider: "cloudflare"

docker_home: "/data/docker"

traefik_network:  "{{ '{{' }} traefik_network {{ '}}' }}"

traefik_users:
  admin: "$2y$05$DG5qSRWLCZfYX6BdHJ7rR.1kUCDA.Gc6tIyRiZ.HNuBnE8aIyKA3q"

traefik_stack:
  name: "Træfik"
  containers:
    - name: traefik
      traefik: yes
      image: traefik
      env: "{{ traefik_env | default( {} ) }}"
      traefik_websecure_middlewares:
        - "traefikauth@file"
      volumes_no_backup:
        - "/var/run/docker.sock:/var/run/docker.sock"
      mountfiles_no_backup:
        - [[ "config/traefik.yaml", "/etc/traefik/traefik.yaml" ]]
        - [[ "config/provider.yaml", "/etc/traefik/provider.yaml" ]]
      labels:
        traefik.http.routers.traefik_traefik_http.service: "api@internal"
        traefik.http.routers.traefik_traefik.service: "api@internal"
      traefik_port: "8080"
      directories:
        - [[ "acme", "/acme" ]]
      directories_no_backup:
        - [[ "logs", "/var/log/traefik" ]]
      fqdn:
        - "{{ traefik_fqdn | default( 'traefik.' + alias_fqdn | default( ansible_host ) | lower ) }}"
      # networks:
      #   - "{{ traefik_network }}"
      network_mode: "host"

...
