---

- name: Apt Update
  apt:
    update-cache: yes

- name: Aptitude must be present
  apt:
    name: aptitude

- name: Check for upgradeable
  apt:
    upgrade: 'yes'
  check_mode: yes
  register: upgradeable

- name: Show me
  debug:
    msg: "{{ upgradeable.stdout_lines }}"

- name: Update all packages to the latest version
  apt:
    upgrade: 'yes'
    state: latest

# # command to install updates and clean up kernel images, etc.
#
# sudo apt update && \
# sudo apt upgrade -y && \
# sudo apt autoremove -y && \
# sudo apt-get purge $(dpkg -l linux-{image,headers}-"[0-9]*" | \
#   awk '/ii/{print $2}' | \
#   grep -ve "$(uname -r | \
#   sed -r 's/-[a-z]+//')")

...
