---

- name: Apt Update
  apt:
    update-cache: yes

- name: Aptitude must be present
  apt:
    name: aptitude

- name: Check for upgradeable
  apt:
    upgrade: Yes
  check_mode: True
  register: upgradeable

- name: Show me
  debug:
    msg: "{{ upgradeable.stdout_lines }}"

- name: Update all packages to the latest version
  apt:
    upgrade: yes
    state: latest

...
