---

- name: Ensure dependencies are installed
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default( package_state ) }}"
  with_items: "{{ install_tools }}"
  become: yes

- name: Ensure folder exists
  file: 
    path: "{{ item }}" 
    state: directory 
    owner: "{{ nagios.user }}" 
    group: "{{ nagios.user }}" 
  with_items:
    - /usr/lib/nagios
    - /var/run/nagios

- name: Ensure plugins are installed
  copy: 
    src: "{{ item }}" 
    dest: "/usr/lib/nagios/plugins/{{ item|basename }}" 
    mode: 0755
  with_fileglob:
    - ./*

- name: Ensure config is installed
  template: 
    src: nrpe.cfg.j2 
    dest: /etc/nagios/nrpe.cfg 
    mode: 0644 
    owner: root 
    group: root
  notify: restart nrpe

- name: Ensure nagios-nrpe-server on client is restarted
  service: 
    name: nagios-nrpe-server 
    state: restarted

- name: test if ufw is installed and active
  command: "ufw status | grep 'Status: active'"
  become: yes
  register: ufw_status

- name: Configure ufw rules
  ufw:
    rule:  "allow"
    port:  "{{ nagios.port }}"
    proto: "tcp"
  become: yes
  when: ufw_status.rc == 0

- name: Configure ufw rules
  ufw:
    rule:  "allow"
    port:  "{{ nagios.port }}"
    proto: "udp"
  become: yes
  when: ufw_status.rc == 0

- name: restart ufw
  service:
    name:  ufw
    state: restarted

...
