---

- hosts: 'docker:!localhost'
  become: yes

  tasks:

    # include_* is processed in place, import_* would be pre-processed, so it should not be used here.
    - include_tasks: "_prepare.yml"

    # Træfik check now has to take place

    # Afer that, run all Docker Stacks
    - name: Run Docker stacks
      include_tasks: "_run.yml"
      with_dict: "{{ docker_stacks }}"
      loop_control:
        loop_var: cur_stack
      when: docker_stacks | length != 0

...
