#!/bin/bash
set -e

OK=0
WARN=1
CRIT=2

source /etc/nagios/ldap.credentials

MASTER=${SERVER[0]}
TIMEOUT=2

SEARCH="timeout $TIMEOUT ldapsearch -D $USER -w $PASSWORD -s base -b $BASE contextCSN -H "

stat=0
failed=""

function getTimestamp {
	echo $($SEARCH "$1" | grep 'contextCSN:' | awk '{print $2}' | cut -f1 -d'.')
}

# Get timestamp from master and fail when master is not reachable
master_timestamp=$(getTimestamp "$MASTER")
if [ -z "$master_timestamp" ] ; then
  echo "Cannot contact master $MASTER"
  exit $CRIT
fi

for replica in "${SERVER[@]}" ; do

  # Skip first value since this is the master
  if [ "$replica" == "${SERVER[0]}" ] ; then
    continue
  fi

  # Get current timestamps from replicas
  timestamp=$(getTimestamp "$replica")

  # Check if timestamp replica - master is the same
  if  [ "$master_timestamp" != "$timestamp" ] && ! [ -z "$timestamp" ] ; then
    failed="$failed $replica"
    stat=1
  fi

  # If no timestmap was returned, fail this node
  if [ -z "$timestamp" ] ; then
    failed="$failed $replica (timeout)"
    stat=2
  fi

done

case $stat in
  0)
    echo "All replicas ${SERVER[@]} are up to date"
    exit $OK
  ;;
  1)
    echo -e "Replicas $failed are not in sync with $MASTER"
    exit $WARN
  ;;
  *)
   echo "Replicas $failed are not in sync with $MASTER"
   exit $CRIT
  ;;
esac
