#!/bin/bash
OK=0
WARN=1
CRIT=2

# get files
files=$(grep "Not copying as --dry-run" /var/log/check_offsite_backup | cut -d" " -f3 | tr ":" " ")

filenumber=$(echo "$files" | wc -l)

if ! [ -z "$files" ] ; then
  if [ $filenumber -le 1 ] ; then
    echo -n "$files is missing from offsite backup"
    exit $WARN
  else
    files=$(echo "$files" | tr '\n' ' ')
    echo -n "$filenumber files are missing from offsite backup. ($files)"
    exit $CRIT
  fi
fi

echo -n "All files are in sync"
exit $OK

