#!/bin/bash

set -x

logFile=/var/log/check_hs3_backup.log
scriptName=hs3-backup-sync

# check if backup is still running
if ps aux | grep "$scriptName" > /dev/null ; then
	status=2
# else get status from file
else
	status=$(grep $(date +%F --date="yesterday") $logFile | cut -d';' -f2 > /dev/null)
fi

case $status in
	0)
		echo "All  backups up to date"
		exit 0
	;;
	1)	
		echo "Backups NOT up to date"
		exit 1
	;;
	2)
		echo "Backup is still running with PID $(ps -C $scriptName -o pid | tail -n 1)"
	;;
	*)
		echo "Error while verifying backup status"
		exit 3
	;;
esac
