galaxy_info:
  author: Christian Walonka, Martin Winter, Felix Kazuya
  company: it-economics GmbH, Independent  
  description: Provision a host to run docker containers
  issue_tracker_url: https://jira.it-economics.de/servicedesk/customer/portal/9/create/274

  license: CC-BY

  min_ansible_version: 2.0

  platforms:
   - name: Ubuntu
     versions:
       - all

  galaxy_tags:
    - docker
