---

- name: Ensure log4shell is installed
  copy:
    src: "log4shell"
    dest: "/usr/local/bin/log4shell"
    mode: 0755

- name: Run log4shell-detector tool
  command: /usr/local/bin/log4shell  scan --exclude /proc  --ignore-warnings --output /tmp/findings.json /
  register: log4shell_output

- name: Debug
  debug: 
    var: log4shell_output.stdout

- name: Save log4shell-detector output locally
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ log4shell_output.stdout }}"
    dest: "log4shell_{{ inventory_hostname }}.log"
    mode: '0755'
  become: false

#- name: Copy to s3
#  s3:
#    aws_access_key: "{{ aws_access_key }}"
#    aws_secret_key: "{{ aws_secret_key }}"
#    bucket: "log4shell.it-economics.de"
#    object: " /tmp/findings.csv"
#    dest: "/"
#    mode: get
#    overwrite: no
