---
###
#applications:
#  stack:
#    app1:          <--- here we are
#      templates:
#        htaccess:
#          src: "wordpress-htaccess.j2"
#          dest: "{{ docker_home }}/wordpress/.htaccess"
#          owner: "777"
#          group: "777"
#        uploadini:
#          src: "uploadini.j2"
#          dest: "{{ docker_home }}/upload.ini"
#          mode: "777"
#          group: "777"
#    app2:          <--- here we are
#      templates:
#        htaccess:
#          src: "wordpress-htaccess.j2"
#          dest: "{{ docker_home }}/wordpress/.htaccess"
#          mode: "777"
#          owner: "777"
#          group: "777"
#        uploadini:
#          src: "uploadini.j2"
#          dest: "{{ docker_home }}/upload.ini"
#    app3:          <--- here we are
##

- name: application
  debug:
    msg: "{{ app }}"
  when: debug is defined and debug == true

- name: Are Templates defined?
  debug:
    msg: "{{ app.value.templates is defined }}"
  when: debug is defined and debug == true

- name: How long are the templates?
  debug:
    msg: "{{ app.value.templates | length }}"
  when: app.value.templates is defined and debug is defined and debug == true

- name: How long are the templates?
  debug:
    msg: "{{ app.value.templates }}"
  when: app.value.templates is defined and debug is defined and debug == true

- name: Create Folder
  file:
   path: "{{ tpl.value.dest | dirname }}"
   recurse: yes
   state: directory
  with_dict: "{{ app.value.templates }}"
  loop_control:
    loop_var: tpl
  when: app.value.templates is defined and app.value.templates | length != 0

- name: "Create Config-Files"
  template:
    src: "{{ tpl.value.src }}"
    dest: "{{ tpl.value.dest }}"
    mode: "{{ tpl.value.mode | default ('755') }}"
    owner: "{{ tpl.value.owner | default ('root') }}"
    group: "{{ tpl.value.group | default ('root') }}"
  with_dict: "{{ app.value.templates }}"
  loop_control:
    loop_var: tpl
  when: app.value.templates is defined and app.value.templates | length != 0

...
