---
traefik_enabled: true

applications:
  proxy_stack:
    traefik:
      name: traefik
      image: traefik:latest
      restartPolicy: always
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "{{ dockerdatapath }}/traefik/web/certs:/certs:ro"
        - "{{ dockerdatapath }}/traefik/traefik.yaml:/etc/traefik/traefik.yaml"
        - "{{ dockerdatapath }}/traefik/provider.yaml:/etc/traefik/provider.yaml"
        - "{{ dockerdatapath }}/traefik/acme:/acme"
        - "{{ dockerdatapath }}/traefik/log:/var/log/traefik"
      labels:
        - "traefik.enable: 'false'"
        - "traefik.enable: 'true'"
        - "traefik.http.routers.api_http.rule: 'Host(`traefik.it-economics.de`)'"
        - "traefik.http.routers.api_http.service: 'api@internal'"
        - "traefik.http.routers.api_http.entrypoints: 'web'"
        - "traefik.http.routers.api_http.middlewares: 'auth@file'"
        - "traefik.http.routers.api.rule: 'Host(`traefik.it-economics.de`)'"
        - "traefik.http.routers.api.entrypoints: 'websecure'"
        - "traefik.http.routers.api.middlewares: 'auth@file'"
        - "traefik.http.routers.api.tls: 'true'"
        - "traefik.http.routers.api.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.api.service: 'api@internal'"
        - "traefik.http.routers.api.tls.domains[0].main: 'it-economics.de'"
        - "traefik.http.routers.api.tls.domains[0].sans: '*.it-economics.de'"
        - "traefik.http.services.traefik.loadbalancer.server.port: '8080'"
      ports:
        - '80:80'
        - '443:443'
        - '8443:8443'     
      networks:
        - "backbone"
        - "database"
