---

- name: Get information about {{ customer }}-{{ hosting_application }} Cloudformation Stack
  cloudformation_info:
    stack_name: "{{ customer }}-{{ hosting_application }}"
    stack_resources: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    security_token: "{{ security_token }}"
    region: "{{ region }}"
  ignore_errors: yes
  register: cloudformation_app_output

- name: Delete {{ customer }}-{{ hosting_application }} Stack
  block:
    - name: Set Vars
      set_fact:
        # backupBucketName: "{{ cloudformation_app_output.cloudformation['{{ stack_name }}'].stack_outputs['backupBucketName'] }}"
        backupBucketName: "531935566054-{{ customer }}-{{ hosting_application }}-backups"

    - name: Delete {{ customer }}-{{ hosting_application }} Cloudformation Stack
      cloudformation:
        stack_name: "{{ customer }}-{{ hosting_application }}"
        state: "absent"
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        security_token: "{{ security_token }}"
        region: "{{ region }}"
      ignore_errors: yes

    - name: Delete {{ customer }}-{{ hosting_application }} S3 Bucket
      s3_bucket:
        name: "{{ backupBucketName }}"
        state: absent
        force: yes
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        security_token: "{{ security_token }}"
        region: "{{ region }}"
      ignore_errors: yes
  when: cloudformation_app_output is defined

...