#! /bin/bash

if [ ! -d /home/ubuntu/.ssh ] ; then
        mkdir -p /home/ubuntu/.ssh
        chmod 700 /home/ubuntu/.ssh
fi

# Fetch public key using HTTP
curl http://169.254.169.254/latest/meta-data/public-keys/0/openssh-key > /tmp/my-key
if [ $? -eq 0 ] ; then
        cat /tmp/my-key > /home/ubuntu/.ssh/authorized_keys
        chmod 600 /home/ubuntu/.ssh/authorized_keys
        rm /tmp/my-key
fi

exit 0
