---

- name: Get information about Hostingbase Cloudformation Stack
  cloudformation_info:
    stack_name: hostingbase
    stack_resources: yes
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    security_token: "{{ security_token }}"
  ignore_errors: yes
  register: cloudformation_base_output

- name: Delete hostinbbase 
  block:
    - name: Set Vars
      set_fact:
        logBucket: "{{ cloudformation_base_output.cloudformation['hostingbase'].stack_resources['logBucket'] }}"
      
    - name: Delete hostingbase cloudformation
      cloudformation:
        stack_name: "hostingbase"
        state: "absent"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
        region: "{{ region }}"

    - name: Delete hostingbase s3 bucket
      s3_bucket:
        region: "{{ region }}"  
        name: "{{ logBucket }}"
        state: absent
        force: yes
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
  when: cloudformation_base_output is defined

...