---

applications:

  wireguard-stack:
    wireguard:
      name: wireguard
      image: "{{ docker_registry }}linuxserver/wireguard"
      restartPolicy: always
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      environment:
        PUID: "1000"
        PGID: "1000"
        TZ: "Europe/London"
        SERVERURL: "hq1-muc.it-economics.de" #optional
        SERVERPORT: "51820" #optional
        PEERS: "1" #optional
        PEERDNS: "auto" #optional
        INTERNAL_SUBNET: "10.13.13.0" #optional
        ALLOWEDIPS: "0.0.0.0/0" #optional
      volumes:
        - "/var/wireguard/config:/config"
        - "/lib/modules:/lib/modules"
      sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
      labels:
        - "traefik.enable: 'false'"
      networks:
        - "backbone"
      ports:
        - 51820:51820/udp

    wireguard-ui:
      name: wireguard-ui
      image: "{{ docker_registry }}ngoduykhanh/wireguard-ui:latest"
      restartPolicy: always
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      environment:
        EMAIL_FROM_ADDRESS: "wireguard@it-economics.de"
        EMAIL_FROM_NAME: "wireguard@it-economics.de"
        SESSION_SECRET: "sdf45fdjkgSDFGSdfjlksdfk"
        WGUI_USERNAME: "admin"
        WGUI_PASSWORD: "IbiBaDidubiBaBu2021!"
        SENDGRID_API_KEY: "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"
      volumes:
        - "/var/wireguard-ui/db:/app/db"
        - "/var/wireguard/config:/etc/wireguard"
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.wgui.loadbalancer.server.port: '5000'"
        - "traefik.http.routers.wgui_http.rule: 'Host(`wgui.it-economics.de`)'"
        - "traefik.http.routers.wgui_http.entrypoints: 'web'"
        - "traefik.http.routers.wgui_http.middlewares: 'forcehttps@file'"
        - "traefik.http.routers.wgui.rule: 'Host(`wgui.it-economics.de`)'"
        - "traefik.http.routers.wgui.entrypoints: 'websecure'"
        - "traefik.http.routers.wgui.tls: 'true'"
        - "traefik.http.routers.wgui.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.wgui.tls.domains[0].main: 'it-economics.de'"
        - "traefik.http.routers.wgui.tls.domains[0].sans: '*.it-economics.de'"
      networks:
        - "backbone"

  openvpn-stack:
    openvpn:
      name: openvpn
      # image: "docker.it-economics.de/proxy/devopsansiblede/openvpn:latest"
      image: 'wheelybird/openvpn-ldap-otp:latest'
      restartPolicy: always
      cap_add:
        - NET_ADMIN
      environment:
        DEBUG: 'false'
        KEY_LENGTH: 4096
        OVPN_MANAGEMENT_ENABLE: 'false'
        OVPN_SERVER_CN: 'connect.it.economics.de'
        OVPN_PORT: 1194
        OVPN_DNS_SEARCH_DOMAIN: 'it-economics.de,int.it-economics.de,muc.it-economics.de'
        OVPN_NAT: 'true'
        OVPN_NETWORK: '10.50.50.0 255.255.255.0'
        OVPN_PROTOCOL: 'udp'
        OVPN_ENABLE_COMPRESSION: 'false' # must be false due to security vulnerability
        LDAP_URI: "{{ openvpn.LDAP_URI }}"
        LDAP_BASE_DN: "{{ openvpn.LDAP_BASE_DN }}"
        LDAP_TLS_VALIDATE_CERT: "{{ openvpn.LDAP_TLS_VALIDATE_CERT }}"
        LDAP_ENCRYPT_CONNECTION: "{{ openvpn.LDAP_ENCRYPT_CONNECTION }}"
        LDAP_LOGIN_ATTRIBUTE: "{{ openvpn.LDAP_LOGIN_ATTRIBUTE }}"
        LDAP_FILTER: "{{ openvpn.LDAP_FILTER }}"
        LDAP_BIND_USER_PASS: "{{ openvpn.LDAP_BIND_USER_PASS }}"
        LDAP_BIND_USER_DN: "{{ openvpn.LDAP_BIND_USER_DN }}"
        # LOG_TO_STDOUT: 'false'
        FAIL2BAN_ENABLED: 'true'
        FAIL2BAN_MAXRETRIES: 10
        ENABLE_OTP: 'false'
        OVPN_TLS_CIPHERS: 'TLS-ECDHE-ECDSA-WITH-CHACHA20-POLY1305-SHA256:TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256:TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256:TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256'
        # OVPN_ROUTES
      volumes:
        - "{{ docker_home }}/openvpn:/etc/openvpn"
      labels:
        - "traefik.enable: 'false'"
      networks:
        - "backbone"
      ports:
        - "1194:1194/udp"

    oldopenvpn:
      name: oldopenvpn
      privileged: true
      image: "{{ docker_registry }}iteconomics/openvpn:42"
      restartPolicy: always
      volumes:
        - '{{ docker_home }}/oldopenvpn/config/ite.conf:/etc/openvpn/ite.conf'
        - '{{ docker_home }}/oldopenvpn/config/ldap.cfg:/etc/openvpn/ldap.cfg'
        - '{{ docker_home }}/oldopenvpn/ssl:/etc/ssl/vpn'
      labels:
        - "traefik.enable: 'false'"
      networks:
        - "backbone"
      ports:
        - 6443:443

...
