---

version: '3'

volumes:
  selenium_shm:

services:

  test-browser:
    ## Use if you want to connect via VNC
    # image: "docker.it-economics.de/proxy/selenium/standalone-firefox-debug"
    image: "${DOCKER_REGISTRY}selenium/standalone-firefox"
    volumes:
      - "selenium_shm:/dev/shm"
    environment:
      SE_OPTS: "-timeout 86400 -browserTimeout 86400"
    ports:
      - "4445:4444"
    labels:
      traefik.enable: "false"

...
