---

ldapports:
  tls:
    ldap01:    '22636'
    ldaptmp:   '23636'
    ldaptest:  '24636'
    ldapcerts: '60636'
  loc:
    ldap01:    '127.0.0.1:12389'
    ldaptmp:   '127.0.0.1:13389'
    ldaptest:  '127.0.0.1:14389'
    ldapcerts: '127.0.0.1:15389'

applications:

  auth_ldap:
    ldap01:
      name:          "auth-ldap01"
      image:         "{{ docker_registry }}devopsansiblede/ldap:latest"
      restartPolicy: "always"
      volumes:
        - "{{ docker_home }}/auth/ldap01/db:/var/lib/ldap"
        - "{{ docker_home }}/auth/ldap01/config:/etc/ldap/slapd.d"
        - "{{ docker_home }}/auth/lego:/lego"
      environment:
        # LDAP_ADMIN_PW
        # LDAP_CONFIG_PW
        LDAPS_PORT:         '636'
        LDAP_DOMAIN:        'it-economics.de'
        LDAP_ORGANISATION:  'it-economics GmbH'
        LDAP_LOGLEVEL:      '16384'
        LEGO_ACCOUNT_EMAIL: 'sysadmin@it-economics.de'
        LEGO_CERT_DOMAIN:   '*.auth.it-economics.de'
        LEGO_DNS_PROVIDER:  'cloudflare'
        CLOUDFLARE_EMAIL:   '{{ cloudflare_email }}'
        CLOUDFLARE_API_KEY: '{{ cloudflare_api_token }}'
      labels:
        - "traefik.enable: false"
      ports:
        - "{{ ldapports.tls.ldap01 }}:636"
        - "{{ ldapports.loc.ldap01 }}:389"
      networks:
        - "database"
      logging:
        driver: "awslogs"
        options:
          awslogs-region: "eu-central-1"
          awslogs-group:  "docker"
          awslogs-stream: "authldap01"
    ldap-tmp:
      name:          "auth-ldap-tmp"
      image:         "{{ docker_registry }}devopsansiblede/ldap:latest"
      restartPolicy: "always"
      volumes:
        - "{{ docker_home }}/auth/ldap-tmp/db:/var/lib/ldap"
        - "{{ docker_home }}/auth/ldap-tmp/config:/etc/ldap/slapd.d"
        - "{{ docker_home }}/auth/lego:/lego"
      environment:
        # LDAP_ADMIN_PW
        # LDAP_CONFIG_PW
        LDAPS_PORT:         '636'
        LDAP_DOMAIN:        'tmp.it-economics.de'
        LDAP_ORGANISATION:  'it-economics GmbH'
        LDAP_LOGLEVEL:      '16384'
        LEGO_ACCOUNT_EMAIL: 'sysadmin@it-economics.de'
        LEGO_CERT_DOMAIN:   '*.auth.it-economics.de'
        LEGO_DNS_PROVIDER:  'cloudflare'
        CLOUDFLARE_EMAIL:   '{{ cloudflare_email }}'
        CLOUDFLARE_API_KEY: '{{ cloudflare_api_token }}'
      labels:
        - "traefik.enable: false"
      ports:
        - "{{ ldapports.tls.ldaptmp }}:636"
        - "{{ ldapports.loc.ldaptmp }}:389"
      networks:
        - "database"
      logging:
        driver: "awslogs"
        options:
          awslogs-region: "eu-central-1"
          awslogs-group:  "docker"
          awslogs-stream: "authldaptmp"
    ldap-test:
      name:          "auth-ldap-test"
      image:         "{{ docker_registry }}devopsansiblede/ldap:latest"
      restartPolicy: "always"
      volumes:
        - "{{ docker_home }}/auth/ldap-test/db:/var/lib/ldap"
        - "{{ docker_home }}/auth/ldap-test/config:/etc/ldap/slapd.d"
        - "{{ docker_home }}/auth/lego:/lego"
      environment:
        # LDAP_ADMIN_PW
        # LDAP_CONFIG_PW
        LDAPS_PORT:         '636'
        LDAP_DOMAIN:        'test.it-economics.de'
        LDAP_ORGANISATION:  'it-economics GmbH'
        LDAP_LOGLEVEL:      '16384'
        LEGO_ACCOUNT_EMAIL: 'sysadmin@it-economics.de'
        LEGO_CERT_DOMAIN:   '*.auth.it-economics.de'
        LEGO_DNS_PROVIDER:  'cloudflare'
        CLOUDFLARE_EMAIL:   '{{ cloudflare_email }}'
        CLOUDFLARE_API_KEY: '{{ cloudflare_api_token }}'
      labels:
        - "traefik.enable: false"
      ports:
        - "{{ ldapports.tls.ldaptest }}:636"
        - "{{ ldapports.loc.ldaptest }}:389"
      networks:
        - "database"
      logging:
        driver: "awslogs"
        options:
          awslogs-region: "eu-central-1"
          awslogs-group:  "docker"
          awslogs-stream: "authldaptmp"

  ldap-certs_stack:
    ldap-certs:
      name:          "ldap-certs"
      image:         "{{ docker_registry }}devopsansiblede/ldap:latest"
      restartPolicy: "always"
      volumes:
        - "{{ docker_home }}/auth/ldap-certs/data/data:/var/lib/ldap"
        - "{{ docker_home }}/auth/ldap-certs/data/config:/etc/ldap/slapd.d"
        - "{{ docker_home }}/auth/lego:/lego"
      environment:
        LDAPS_PORT:         '636'
        LDAP_DOMAIN:        'it-economics.de'
        LDAP_ORGANISATION:  'it-economics GmbH'
        LDAP_LOGLEVEL:      '16384'
        LEGO_ACCOUNT_EMAIL: 'sysadmin@it-economics.de'
        LEGO_CERT_DOMAIN:   '[ "nlb.it-economics.de", "ldap-certs.it-economics.de" ]'
        LEGO_DNS_PROVIDER:  'cloudflare'
        CLOUDFLARE_EMAIL:   '{{ cloudflare_email }}'
        CLOUDFLARE_API_KEY: '{{ cloudflare_api_token }}'
      labels:
        - "traefik.enable: false"
      ports:
        - "{{ ldapports.tls.ldapcerts }}:636"
        - "{{ ldapports.loc.ldapcerts }}:389"
      networks:
        - "database"
      logging:
        driver: "awslogs"
        options:
          awslogs-region: "eu-central-1"
          awslogs-group:  "docker"
          awslogs-stream: "authldaptmp"

  directory-test_stack:
    directory-test:
      name: directory-test
      image: "{{ docker_registry }}iteconomics/directory:testing"
      restartPolicy: always
      volumes:
        - "{{ docker_home }}/certs/data/data:/var/www/html/storage/app/certs"
        - "{{ docker_home }}/certs/data/templates:/var/www/html/storage/app/templates"
        - "{{ docker_home }}/directory-test/config/.env:/var/www/html/.env"
        - "{{ docker_home }}/directory-test/database.sqlite:/var/www/html/database/database.sqlite"
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.directory-test.loadbalancer.server.port: '80'"
        - "traefik.http.routers.directory-test_http.rule: 'Host(`directory-test.it-economics.de`)'"
        - "traefik.http.routers.directory-test_http.entrypoints: 'web'"
        - "traefik.http.routers.directory-test_http.middlewares: 'forcehttps@file'"
        - "traefik.http.routers.directory-test.rule: 'Host(`directory-test.it-economics.de`)'"
        - "traefik.http.routers.directory-test.entrypoints: 'websecure'"
        - "traefik.http.routers.directory-test.tls: 'true'"
        - "traefik.http.routers.directory-test.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.directory-test.tls.domains[0].main: 'it-economics.de'"
        - "traefik.http.routers.directory-test.tls.domains[0].sans: '*.it-economics.de'"
      environment:
        MODS:   'ssl ldap authnz_ldap php7 rewrite headers'
        PHPINI: '{"post_max_size":"25M","upload_max_filesize":"25M","max_execution_time":"300","memory_limit":"512M"}'
      networks:
        - "backbone"
        - "database"

  directory_stack:
    directory:
      name: directory
      image: "{{ docker_registry }}iteconomics/directory:latest"
      restartPolicy: always
      volumes:
        - "{{ docker_home }}/directory/config/.env:/var/www/html/.env"
        - "{{ docker_home }}/directory/database.sqlite:/var/www/html/database/database.sqlite"
        - "{{ docker_home }}/certs/data/data:/var/www/html/storage/app/certs"
        - "{{ docker_home }}/certs/data/templates:/var/www/html/storage/app/templates"
        - "{{ docker_home }}/directory/cronjobs:/etc/cron.d/docker"
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.directory.loadbalancer.server.port: '80'"
        - "traefik.http.routers.directory_http.rule: 'Host(`directory.it-economics.de`)'"
        - "traefik.http.routers.directory_http.entrypoints: 'web'"
        - "traefik.http.routers.directory_http.middlewares: 'forcehttps@file'"
        - "traefik.http.routers.directory.rule: 'Host(`directory.it-economics.de`)'"
        - "traefik.http.routers.directory.entrypoints: 'websecure'"
        - "traefik.http.routers.directory.tls: 'true'"
        - "traefik.http.routers.directory.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.directory.tls.domains[0].main: 'it-economics.de'"
        - "traefik.http.routers.directory.tls.domains[0].sans: '*.it-economics.de'"
      environment:
        START_CRON: 1
        MODS:       'ssl ldap authnz_ldap php7 rewrite headers'
        PHPINI:     '{"post_max_size":"25M","upload_max_filesize":"25M","max_execution_time":"300","memory_limit":"512M"}'
      networks:
        - "backbone"
        - "database"

  freeradius-stack:
    freeradius:
      name: "freeradius"
      image: "{{ docker_registry }}iteconomics/freeradius:latest"
      container_name: "freeradius"
      restartPolicy: "always"
      ports:
        - "1812:1812/udp"
        - "1813:1813/udp"
      volumes:
        - "{{ docker_home }}/auth/freeradius/config/ldap:/etc/freeradius/3.0/mods-available/ldap"
        - "{{ docker_home }}/auth/freeradius/config/radiusd.conf:/etc/freeradius/3.0/radiusd.conf"
        - "{{ docker_home }}/auth/freeradius/certs:/certs"
        - "{{ docker_home }}/auth/freeradius/config/clients.conf:/etc/freeradius/3.0/clients.conf"
      networks:
        - "backbone"
      labels:
        - "traefik.enable: 'false'"
      logging:
        driver: "awslogs"
        options:
          awslogs-region: "eu-central-1"
          awslogs-group: "docker"
          awslogs-stream: "freeradius"

...
