---

mount_path: "app"
traefik_network: "proxy"

data_mount_opts:
  - uid=1000
  - gid=1000
  - dir_mode=0775
  - auto
  - credentials=/root/mount.cifs

templates:
  - src: "traefik.yaml.j2"
    dest: "{{ docker_bind_path }}/traefik/traefik.yaml"
  - src: "provider.yaml.j2"
    dest: "{{ docker_bind_path }}/taefik/provider.yaml"

traefikapp:
  traefik_stack:
    traefik:
      name:          traefik
      image:         traefik
      restartPolicy: always
      network_mode:  host
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "{{ docker_bind_path }}/traefik/traefik.yaml:/etc/traefik/traefik.yaml"
        - "{{ docker_bind_path }}/traefik/provider.yaml:/etc/traefik/provider.yaml"
        - "{{ docker_bind_path }}/traefik/logs:/var/log/traefik"
        - "{{ docker_bind_path }}/traefik/certs:/certs"
      labels:
        - "traefik.enable: 'true'"

...
