---

fqdn_postfix: ".star.galaxy.io"

stage_root: "lb"
mount_path: "app"

lb_config:
  jira_prod:
    app: "jira"
    url: "works-de{{ fqdn_postfix }}"
    servers:
      - "usrv50113.star.galaxy.io"
  confluence_prod:
    app: "confluence"
    url: "knows-de{{ fqdn_postfix }}"
    servers:
      - "usrv50113.star.galaxy.io"
  jira_test:
    app: "jira"
    url: "test-works-de{{ fqdn_postfix }}"
    servers:
      - "usrv59113.star.galaxy.io"
  confluence_test:
    app: "confluence"
    url: "test-knows-de{{ fqdn_postfix }}"
    servers:
      - "usrv59113.star.galaxy.io"
  jira_dev:
    app: "jira"
    url: "dev-works-de{{ fqdn_postfix }}"
    servers:
      - "usrv59113.star.galaxy.io"
  confluence_dev:
    app: "confluence"
    url: "dev-knows-de{{ fqdn_postfix }}"
    servers:
      - "usrv59113.star.galaxy.io"

templates:
  - src: "traefik.yaml.j2"
    dest: "{{ docker_bind_path }}/traefik/traefik.yaml"
  - src: "provider.yaml.j2"
    dest: "{{ docker_bind_path }}/traefik/provider.yaml"

traefik_network: "proxy"

applications:

  traefik_stack:

    traefik:
      name:          traefik
      image:         traefik
      restartPolicy: always
      network_mode:  host
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "{{ docker_bind_path }}/traefik/traefik.yaml:/etc/traefik/traefik.yaml"
        - "{{ docker_bind_path }}/traefik/provider.yaml:/etc/traefik/provider.yaml"
        - "{{ docker_bind_path }}/traefik/logs:/var/log/traefik"
        - "{{ docker_bind_path }}/traefik/certs:/certs"
      labels:
        - "traefik.enable: 'true'"

...
