---
docker_host: true
traefik_enabled: false
remote: true
debug: true
# we want to install this server as Docker server
composerFilePath: "/mnt/shared/compose"
traefik_network: proxy
internal_network: internal
traefik_fqdn: "traefik.finance.it-economics.de"
docker_registry: 'docker.it-economics.de/proxy/'
docker_home: "/mnt/shared/applications"

...
