---

applications:
  teamsurvey-api_stack:
    teamsurvey-api:
      name: teamsurvey-api
      image: "{{ docker_registry }}iteconomics/teamsurvey-api:latest"
      restartPolicy: always
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.teamsurvey-api.loadbalancer.server.port: '8080'"
        - "traefik.http.routers.teamsurvey-api_http.rule: 'Host(`teamsurvey-api.it-economics.de`)'"
        - "traefik.http.routers.teamsurvey-api_http.entrypoints: 'web'"
        - "traefik.http.routers.teamsurvey-api_http.middlewares: 'forcehttps@file'"
        - "traefik.http.routers.teamsurvey-api.rule: 'Host(`teamsurvey-api.it-economics.de`)'"
        - "traefik.http.routers.teamsurvey-api.entrypoints: 'websecure'"
        - "traefik.http.routers.teamsurvey-api.tls: 'true'"
        - "traefik.http.routers.teamsurvey-api.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.teamsurvey-api.tls.domains[0].main: 'it-economics.de'"
        - "traefik.http.routers.teamsurvey-api.tls.domains[0].sans: '*.it-economics.de'"
      environment:
        MSQL_USER: "{{ teamsurveyapi.MYSQL_USER }}"
        MSQL_PASS: "{{ teamsurveyapi.MYSQL_PASS }}"
        MSQL_HOST: "{{ teamsurveyapi.MYSQL_HOST }}"
        MONGO_USER: "{{ teamsurveyapi.MONGO_USER }}"
        MONGO_PASS: "{{ teamsurveyapi.MONGO_PASS }}"
        MONGO_HOST: "{{ teamsurveyapi.MONGO_HOST }}"
      ports:
      - "127.0.0.1:5050:5050"
      networks:
        - "database"
        - "backbone"
    teamsurvey-api_db:
      name: teamsurvey-api_db
      image: "{{ docker_registry }}library/mongo:4.2"
      restartPolicy: always
      labels:
        - "traefik.enable: 'false'"
      environment:
        MONGO_INITDB_ROOT_USERNAME: "{{ teamsurveyapi.MONGO_USER }}"
        MONGO_INITDB_ROOT_PASSWORD: "{{ teamsurveyapi.MONGO_PASS }}"
        MONGO_INITDB_DATABASE: "{{ teamsurveyapi.DATABASE }}"
      networks:
        - "database"
      volumes:
        - "{{ docker_home }}/teamsurvey-api/db/data:/data/db"

  teamsurvey-api-testing_stack:
    teamsurvey-api-testing:
      name: teamsurvey-api-testing
      image: "{{ docker_registry }}iteconomics/teamsurvey-api:latest"
      restartPolicy: always
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.teamsurvey-api-testing.loadbalancer.server.port: '8080'"
        - "traefik.http.routers.teamsurvey-api-testing_http.rule: 'Host(`teamsurvey-api-testing.it-economics.de`)'"
        - "traefik.http.routers.teamsurvey-api-testing_http.entrypoints: 'web'"
        - "traefik.http.routers.teamsurvey-api-testing_http.middlewares: 'forcehttps@file'"
        - "traefik.http.routers.teamsurvey-api-testing.rule: 'Host(`teamsurvey-api-testing.it-economics.de`)'"
        - "traefik.http.routers.teamsurvey-api-testing.entrypoints: 'websecure'"
        - "traefik.http.routers.teamsurvey-api-testing.tls: 'true'"
        - "traefik.http.routers.teamsurvey-api-testing.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.teamsurvey-api-testing.tls.domains[0].main: 'it-economics.de'"
        - "traefik.http.routers.teamsurvey-api-testing.tls.domains[0].sans: '*.it-economics.de'"
      environment:
        MSQL_USER: "{{ teamsurveyapi.MYSQL_USER }}"
        MSQL_PASS: "{{ teamsurveyapi.MYSQL_PASS }}"
        MSQL_HOST: "{{ teamsurveyapi.MYSQL_HOST }}"
        MONGO_USER: "{{ teamsurveyapitesting.MONGO_USER }}"
        MONGO_PASS: "{{ teamsurveyapitesting.MONGO_PASS }}"
        MONGO_HOST: "{{ teamsurveyapitesting.MONGO_HOST }}"
      ports:
      - "127.0.0.1:5051:5050"
      networks:
        - "database"
        - "backbone"
    teamsurvey-api-testing_db:
      name: teamsurvey-api-testing_db
      image: "{{ docker_registry }}library/mongo:4.2"
      restartPolicy: always
      labels:
        - "traefik.enable: 'false'"
      environment:
        MONGO_INITDB_ROOT_USERNAME: "{{ teamsurveyapitesting.MONGO_USER }}"
        MONGO_INITDB_ROOT_PASSWORD: "{{ teamsurveyapitesting.MONGO_PASS }}"
        MONGO_INITDB_DATABASE: "{{ teamsurveyapitesting.DATABASE }}"
      networks:
        - "database"
      volumes:
        - "{{ docker_home }}/teamsurvey-api-testing/db/data:/data/db"

  worksuite:
    teamsurvey-ssh:
      name: teamsurvey_ssh
      image: "{{ docker_registry }}devopsansiblede/worksuite:latest"
      restartPolicy: always
      labels:
        - "traefik.enable: 'false'"
      ports:
      - "50022:22"
      networks:
        - "database"
        - "backbone"
      volumes:
        - "{{ docker_home }}//worksuite/teamsurvey_ssh/:/root/.ssh:ro"

  apps_stack:
    achievo:
      name: achievo
      image: "{{ docker_registry }}iteconomics/apache:latest"
      restartPolicy: always
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.achievo.loadbalancer.server.port: '80'"
        - "traefik.http.routers.achievo_http.rule: 'Host(`achievo.it-economics.de`)'"
        - "traefik.http.routers.achievo_http.entrypoints: 'web'"
        - "traefik.http.routers.achievo_http.middlewares: 'forcehttps@file'"
        - "traefik.http.routers.achievo.rule: 'Host(`achievo.it-economics.de`)'"
        - "traefik.http.routers.achievo.entrypoints: 'websecure'"
        - "traefik.http.routers.achievo.tls: 'true'"
        - "traefik.http.routers.achievo.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.achievo.tls.domains[0].main: 'it-economics.de'"
        - "traefik.http.routers.achievo.tls.domains[0].sans: '*.it-economics.de'"
      environment:
        OpenID_ClientSecret: "{{ achievo.OpenID_ClientSecret }}"
        OpenID_ClientID: "{{ achievo.OpenID_ClientID }}"
        OpenID_MetaDataURL: "{{ achievo.OpenID_MetaDataURL }}"
        OpenID_RedirectURL: "{{ achievo.OpenID_RedirectURL }}"
        OpenID_Mailpost: "{{ achievo.OpenID_Mailpost }}"
        LDAP_Host: "{{ achievo.LDAP_Host }}"
        LDAP_Group: "{{ achievo.LDAP_Group }}"
        LDAP_BindDN: "{{ ldap_directory_user }}"
        LDAP_BindPassword: "{{ ldap_directory_pass }}"
      networks:
        - "backbone"
        - "database"
      volumes:
        - "{{ docker_home }}/achievo/config:/config"
        - "{{ docker_home }}/achievo/data:/var/www/html"
    reporting:
      name: reporting
      image: "{{ docker_registry }}iteconomics/apache:latest"
      restartPolicy: always
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.reporting.loadbalancer.server.port: '80'"
        - "traefik.http.routers.reporting_http.rule: 'Host(`reporting.it-economics.de`)'"
        - "traefik.http.routers.reporting_http.entrypoints: 'web'"
        - "traefik.http.routers.reporting_http.middlewares: 'forcehttps@file'"
        - "traefik.http.routers.reporting.rule: 'Host(`reporting.it-economics.de`)'"
        - "traefik.http.routers.reporting.entrypoints: 'websecure'"
        - "traefik.http.routers.reporting.tls: 'true'"
        - "traefik.http.routers.reporting.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.reporting.tls.domains[0].main: 'it-economics.de'"
        - "traefik.http.routers.reporting.tls.domains[0].sans: '*.it-economics.de'"
      environment:
        OpenID_ClientSecret: "{{ reporting.OpenID_ClientSecret }}"
        OpenID_ClientID: "{{ reporting.OpenID_ClientID }}"
        OpenID_MetaDataURL: "{{ reporting.OpenID_MetaDataURL }}"
        OpenID_RedirectURL: "{{ reporting.OpenID_RedirectURL }}"
        OpenID_Mailpost: "{{ reporting.OpenID_Mailpost }}"
        LDAP_Host: "{{ reporting.LDAP_Host }}"
        LDAP_Group: "{{ reporting.LDAP_Group }}"
        LDAP_BindDN: "{{ ldap_directory_user }}"
        LDAP_BindPassword: "{{ ldap_directory_pass }}"
      networks:
        - "backbone"
        - "database"
      volumes:
        - "{{ docker_home }}/reporting/config:/config"
        - "{{ docker_home }}/reporting/data:/var/www/html"
    apps-database:
      name: apps-database
      image: "{{ docker_registry }}library/mysql:5.5"
      restartPolicy: always
      labels:
        - "traefik.enable: 'false'"
      environment:
        MSQL_USER: "{{ teamsurveyapi.MYSQL_USER }}"
        MSQL_PASS: "{{ teamsurveyapi.MYSQL_PASS }}"
        MSQL_HOST: "{{ teamsurveyapi.MYSQL_HOST }}"
        MYSQL_ROOT_PASSWORD: "{{ teamsurveyapi.MYSQL_PASS }}"
      ports:
      - "127.0.0.1:3306:3306"
      networks:
        - "database"
      volumes:
        - "{{ docker_home }}/database/config:/config"
        - "{{ docker_home }}/database/data:/var/www/html"

  alfresco-stack:
    alfresco-prd:
      name: alfresco-prd
      image: "{{ docker_registry }}iteconomics/alfresco"
      container_name: alfresco-prd
      restartPolicy: always
      labels:
        - "traefik.enable: 'false'"
      volumes:
        - "{{ docker_home }}/alfrescp/config:/config"
        - "{{ docker_home }}/alfresco/data:/var/www/html"
    alfresco-prd_web:
      name: alfresco_web
      image: iteconomics/apache
      container_name: alfresco-prd_web
      restartPolicy: always
      labels:
        - "traefik.enable: 'false'"
      environment:
        MODS: "proxy proxy_ajp ssl headers"
    alfresco-prd_db:
      name: alfresco-prd_db
      image: mysql:5.6
      container_name: alfresco-prd_db
      restartPolicy: always
      labels:
        - "traefik.enable: 'false'"
      environment:
        MYSQL_ROOT_PASSWORD: "{{ alfresco.MYSQL_ROOT_PASSWORD }}"
        MYSQL_DATABASE: "{{ alfresco.MYSQL_DATABASE }}"
        MYSQL_USER: "{{ alfresco.MYSQL_USER }}"
        MYSQL_PASSWORD: "{{ alfresco.MYSQL_PASSWORD }}"
      volumes:
        - "{{ docker_home }}/alfresco/db/config:/etc/mysql/conf.d"
        - "{{ docker_home }}/alfresco/db/data:/var/lib/mysql"
      networks:
        - "database"

...
