---

applications:
  prd_stack:
    jira-prd:
      name: "{{ jiraprd.app }}-{{ jiraprd.stage }}"
      image: "{{ JIRAIMAGE }}"
      restartPolicy: "{{ RESTARTPOLICY }}"
      volumes:
        - "/mnt/data/{{ jiraprd.app }}/data:/var/atlassian/application-data/{{ jiraprd.app }}/:rw"
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.{{ jiraprd.app }}{{ jiraprd.stage }}.loadbalancer.server.port: '8080'"
        - "traefik.http.routers.{{ jiraprd.app }}{{ jiraprd.stage }}_http.rule: 'Host(`{{ jiraprd.url }}`)'"
        - "traefik.http.routers.{{ jiraprd.app }}{{ jiraprd.stage }}_http.entrypoints: 'web'"
        - "traefik.http.routers.{{ jiraprd.app }}{{ jiraprd.stage }}_http.middlewares: 'forcehttps@file'"
        - "traefik.http.routers.{{ jiraprd.app }}{{ jiraprd.stage }}.rule: 'Host(`{{ jiraprd.url }}`)'"
        - "traefik.http.routers.{{ jiraprd.app }}{{ jiraprd.stage }}.entrypoints: 'websecure'"
        - "traefik.http.routers.{{ jiraprd.app }}{{ jiraprd.stage }}.tls: 'true'"
      networks:
        - backbone
    confluence-prd:
      name: "{{ confluenceprd.app }}-{{ confluenceprd.stage }}"
      image: "{{ CONFLUENCEIMAGE }}"
      restartPolicy: "{{ RESTARTPOLICY }}"
      volumes:
        - "/mnt/data/{{ confluenceprd.app }}/data:/var/atlassian/application-data/{{ confluenceprd.app }}/:rw"
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.{{ confluenceprd.app }}{{ confluenceprd.stage }}.loadbalancer.server.port: '8080'"
        - "traefik.http.routers.{{ confluenceprd.app }}{{ confluenceprd.stage }}_http.rule: 'Host(`{{ confluenceprd.url }}`)'"
        - "traefik.http.routers.{{ confluenceprd.app }}{{ confluenceprd.stage }}_http.entrypoints: 'web'"
        - "traefik.http.routers.{{ confluenceprd.app }}{{ confluenceprd.stage }}_http.middlewares: 'forcehttps@file'"
        - "traefik.http.routers.{{ confluenceprd.app }}{{ confluenceprd.stage }}.rule: 'Host(`{{ confluenceprd.url }}`)'"
        - "traefik.http.routers.{{ confluenceprd.app }}{{ confluenceprd.stage }}.entrypoints: 'websecure'"
        - "traefik.http.routers.{{ confluenceprd.app }}{{ confluenceprd.stage }}.tls: 'true'"
      networks:
        - backbone
