---
#
# MAIN FILE to create a new USER ACCOUNT in ITE systems
#

- name: Fetch data from ticket system
  import_playbook: gather_data.yml

- name: Confirmation
  hosts: localhost
  tasks:
    - pause: prompt="Create user __ {{ hostvars['localhost']['user']['registration']['user']['username'] }} __ in environment __ {{ env }} __ and system __ {{ hostvars.get('localhost').get('ldap_url') }} __, press ENTER to continue (abort with ctrl+c)."
      when: env == 'production'

- name: Generate SSL certificate
  import_playbook: ssl.yml

- name: Upload certificate to LDAP
  import_playbook: ssl_ldap.yml

- name: Upload SSL certificate
  import_playbook: ssl_upload.yml

- name: Cleanup temp files
  import_playbook: cleanup.yml
  
- name: Create Mail account
  include: tm-mittelstand.yml

- name: Send welcome mail
  import_playbook: welcomemail.yml
