---

- name: Ensure dependencies are installed
  apt:
    state: present 
    pkg:
    - unzip
    - libwww-perl
    - libdatetime-perl

- name: Unarchive scripts
  unarchive:
    src: "{{ monitoring_url }}"
    dest: /usr/local/bin
    copy: no

- name: Ensure aws monitoring user exists
  user:
    name: awsmon

- name: Ensure disk monitoring cron job is enabled
  cron: 
    user: awsmon
    name: 'disk-space-avail-{{ item }}'
    minute: '{{ monitoring_minute }}'
    hour: '{{ monitoring_hour }} '
    job: '/usr/local/bin/aws-scripts-mon/mon-put-instance-data.pl --from-cron --auto-scaling --disk-space-avail --disk-path={{ item }}'
  with_items: '{{ monitoring_paths }}'

- name: Ensure memory monitoring cron job is enabled
  cron:
    user: awsmon
    name: 'memory-available'
    minute: '{{ monitoring_minute }}'
    hour: '{{ monitoring_hour }}'
    job: '/usr/local/bin/aws-scripts-mon/mon-put-instance-data.pl --from-cron --auto-scaling --mem-avail'

- name: Ensure cache directory exists
  file:
    path: /var/tmp/aws-mon
    state: directory
    owner: awsmon

- name: Ensure scripts are executable
  shell: "chmod a+x /usr/local/bin/aws-scripts-mon/*"

...