---

- name: Run {{ app.lambda.lambda_name}} Lambda
  execute_lambda:
    region: "{{ region }}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    security_token: "{{ security_token }}"
    name: "{{ app.lambda.lambda_name}}"
    payload: "{{ app.lambda.lambda_payload }}"
  
...