---

teamsurveyapi.MYSQL_USER: "teamsurvey"
teamsurveyapi.MYSQL_PASS: "8_wSAr(q55B_6Tl"
teamsurveyapi.MYSQL_HOST: "172.19.0.3"
teamsurveyapi.MONGO_USER: "teamsurvey"
teamsurveyapi.MONGO_PASS: "ArNr6gFbkg9Fhfyn"
teamsurveyapi.MONGO_HOST: "teamsurvey-api_db"
teamsurveyapi.DATABASE: "achievo"

teamsurveyapitesting.MYSQL_USER: "teamsurvey"
teamsurveyapitesting.MYSQL_PASS: "8_wSAr(q55B_6Tl"
teamsurveyapitesting.MYSQL_HOST: "172.19.0.3"
teamsurveyapitesting.MONGO_USER: "teamsurvey-testing"
teamsurveyapitesting.MONGO_PASS: "ArNr6gFbkg9Fhfyn"
teamsurveyapitesting.MONGO_HOST: "teamsurvey-api-testing_db"
teamsurveyapitesting.DATABASE: "achievo"
...
