---

applications:
  teamsurvey-api_stack:
    teamsurvey-api:
      name: teamsurvey-api
      image: iteconomics/teamsurvey-api:latest
      restartPolicy: always
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.teamsurvey-api.loadbalancer.server.port: '8080'"
        - "traefik.http.routers.teamsurvey-api_http.rule: 'Host(`teamsurvey-api.it-economics.de`)'"
        - "traefik.http.routers.teamsurvey-api_http.entrypoints: 'web'"
        - "traefik.http.routers.teamsurvey-api_http.middlewares: 'forcehttps@file'"
        - "traefik.http.routers.teamsurvey-api.rule: 'Host(`teamsurvey-api.it-economics.de`)'"
        - "traefik.http.routers.teamsurvey-api.entrypoints: 'websecure'"
        - "traefik.http.routers.teamsurvey-api.tls: 'true'"
        - "traefik.http.routers.teamsurvey-api.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.teamsurvey-api.tls.domains[0].main: 'it-economics.de'"
        - "traefik.http.routers.teamsurvey-api.tls.domains[0].sans: '*.it-economics.de'"
      environment:
        MSQL_USER: "{{ teamsurvey-api.MYSQL_USER }}"
        MSQL_PASS: "{{ teamsurvey-api.MYSQL_PASS }}"
        MSQL_HOST: "{{ teamsurvey-api.MYSQL_HOST }}"
        MONGO_USER: "{{ teamsurvey-api.MONGO_USER }}"
        MONGO_PASS: "{{ teamsurvey-api.MONGO_PASS }}"
        MONGO_HOST: "{{ teamsurvey-api.MONGO_HOST }}"
      ports:
      - "127.0.0.1:5050:5050"
      networks:
        - "database"
        - "backbone"
    teamsurvey-api_db:
      name: teamsurvey-api_db
      image: mongo:latest
      restartPolicy: always
      labels:
        - "traefik.enable: 'false'"
      environment:
        MSQL_USER: "{{ teamsurveyapi.MYSQL_USER }}"
        MSQL_PASS: "{{ teamsurveyapi.MYSQL_PASS }}"
        MSQL_HOST: "{{ teamsurveyapi.MYSQL_HOST }}"
        MONGO_INITDB_ROOT_USERNAME: "{{ teamsurveyapi.MONGO_USER }}"
        MONGO_INITDB_ROOT_PASSWORD: "{{ teamsurveyapi.MONGO_PASS }}"
        MONGO_INITDB_DATABASE: "{{ teamsurveyapi.DATABASE }}"
      networks:
        - "database"
      volumes:
        - "/mnt/shared/applications/appstore/teamsurvey-api/db/data:/data/db"

  teamsurvey-api-testing_stack:
    teamsurvey-api-testing:
      name: teamsurvey-api-testing
      image: iteconomics/teamsurvey-api:latest
      restartPolicy: always
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.teamsurvey-api-testing.loadbalancer.server.port: '8080'"
        - "traefik.http.routers.teamsurvey-api-testing_http.rule: 'Host(`teamsurvey-api-testing.it-economics.de`)'"
        - "traefik.http.routers.teamsurvey-api-testing_http.entrypoints: 'web'"
        - "traefik.http.routers.teamsurvey-api-testing_http.middlewares: 'forcehttps@file'"
        - "traefik.http.routers.teamsurvey-api-testing.rule: 'Host(`teamsurvey-api-testing.it-economics.de`)'"
        - "traefik.http.routers.teamsurvey-api-testing.entrypoints: 'websecure'"
        - "traefik.http.routers.teamsurvey-api-testing.tls: 'true'"
        - "traefik.http.routers.teamsurvey-api-testing.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.teamsurvey-api-testing.tls.domains[0].main: 'it-economics.de'"
        - "traefik.http.routers.teamsurvey-api-testing.tls.domains[0].sans: '*.it-economics.de'"
      environment:
        MSQL_USER: "{{ teamsurveyapitesting.MYSQL_USER }}"
        MSQL_PASS: "{{ teamsurveyapitesting.MYSQL_PASS }}"
        MSQL_HOST: "{{ teamsurveyapitesting.MYSQL_HOST }}"
        MONGO_USER: "{{ teamsurveyapitesting.MONGO_USER }}"
        MONGO_PASS: "{{ teamsurveyapitesting.MONGO_PASS }}"
        MONGO_HOST: "{{ teamsurveyapitesting.MONGO_HOST }}"
      ports:
      - "127.0.0.1:5051:5050"
      networks:
        - "database"
        - "backbone"
    teamsurvey-api-testing_db:
      name: teamsurvey-api-testing_db
      image: mongo:latest
      restartPolicy: always
      labels:
        - "traefik.enable: 'false'"
      environment:
        MSQL_USER: "{{ teamsurvey-api-testing.MYSQL_USER }}"
        MSQL_PASS: "{{ teamsurvey-api-testing.MYSQL_PASS }}"
        MSQL_HOST: "{{ teamsurvey-api-testing.MYSQL_HOST }}"
        MONGO_INITDB_ROOT_USERNAME: "{{ teamsurvey-api-testing.MONGO_USER }}"
        MONGO_INITDB_ROOT_PASSWORD: "{{ teamsurvey-api-testing.MONGO_PASS }}"
        MONGO_INITDB_DATABASE: "{{ teamsurvey-api-testing.DATABASE }}"
      networks:
        - "database"
      volumes:
        - "/mnt/shared/applications/appstore/teamsurvey-api-testing/db/data:/data/db"

  apps:
    apps-database:
      name: apps-database
      image: mysql:5.5 
      restartPolicy: always
      labels:
        - "traefik.enable: 'false'"
      environment:
        MSQL_USER: "{{ teamsurvey-api-testing.MYSQL_USER }}"
        MSQL_PASS: "{{ teamsurvey-api-testing.MYSQL_PASS }}"
        MSQL_HOST: "{{ teamsurvey-api-testing.MYSQL_HOST }}"
      ports:
      - "127.0.0.1:3306:3306"
      networks:
        - "database"
