---

# TODO A maximum of 4 levels is supported
# because we check if the second from the left equals the third from the right

- name: set DNS entry
  block:
    - name: Ensure DNS Record is set
      cloudflare_dns:
        zone: "{{ app.hostname.split('.')[-2] }}.{{ app.hostname.split('.')[-1] }}"
        record: "{{ app.hostname.split('.')[0] }}{%if app.hostname.split('.')[1] == app.hostname.split('.')[-3] %}.{{ app.hostname.split('.')[1] }}{%endif%}"
        type: CNAME 
        value: "{{ traefik_fqdn }}"
        account_email: "{{ cloudflare_email }}"
        account_api_token: "{{ cloudflare_api_token }}"
        state: present
      when: skipdns is undefined

  rescue:
    - name: DNS Error Handling
      pause: prompt="Please remove the existing Records for {{ app.hostname }}"

    - name: Ensure DNS Record is set
      cloudflare_dns:
        zone: "{{ app.hostname.split('.')[-2] }}.{{ app.hostname.split('.')[-1] }}"
        record: "{{ app.hostname.split('.')[0] }}{%if app.hostname.split('.')[1] == app.hostname.split('.')[-3] %}.{{ app.hostname.split('.')[1] }}{%endif%}"
        type: CNAME 
        value: "{{ traefik_fqdn }}"
        account_email: "{{ cloudflare_email }}"
        account_api_token: "{{ cloudflare_api_token }}"
        state: present

...
