- name: Install required software
  hosts: atlassian_application
  remote_user: ubuntu
  become: yes

  roles:
    - update-all-packages
    - awscli
    - docker_host
    - awsmon
    - awslogs_cloudwatch
    - awsefs
    - swapfile
    - atlassian_aws
    - sophos-install
    - unattended-upgrades
    - ntpd
    - authorized_keys

  tasks:
    - name: Ensure dependencies are installed
      apt:
        state: present
        update_cache: yes
        pkg:
        - parted
        - postgresql-client
        - xmlstarlet
        - gzip
        - openssl

    - name: Pre download images
      command: docker pull {{ item }}
      with_items:
        - "iteconomics/confluence:hosting" #confluence managed hosting
        - "iteconomics/confluence-ite:latest" #confluence it-e
        - "iteconomics/jira:hosting" #jira managed hosting
        - "iteconomics/jira-ite:latest" #jira it-e
        - "iteconomics/bitbucket:hosting"
        - "postgres:{{ postgres_version }}"

    - name: Wait until instance is ready to be bundled
      pause: seconds=90
