---

- name: Create conf to Disable filesystems
  lineinfile:
    path: /etc/modprobe.d/{{ item }}.conf
    line: install {{ item }} /bin/true
    create: yes
    with_items:
      - cramfs
      - freevxfs
      - jffs2
      - hfs
      - hfsplus
      - udf

- name: Disable filesystems
  command: rmmod {{ item }}
  with_items:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - udf

# Only root user can read/write to the grub.cfg
- name: Configure permissions on bootloader
  command: chown root:root /boot/grub/grub.cfg && chmod og-rwx /boot/grub/grub.cfg

# Set correct ownership to prevent incorrect or misleading information for users after login
- name: Configure permissions on motd
  command: chown root:root /etc/motd && chmod 644 /etc/motd

# Uninstall telnet
- name: Uninstall telnet
  command: apt-get remove telnet

# Restrict access to crontab
- name: Restrict access to crontab
  command: chown root:root /etc/crontab && chmod og-rwx /etc/crontab

# Restrict access to cron hourly
- name: Restrict access to cron hourly
  command: chown root:root /etc/cron.hourly && chmod og-rwx /etc/cron.hourly

# Restrict access to cron daily
- name: Restrict access to cron daily
  command: chown root:root /etc/cron.daily && chmod og-rwx /etc/cron.daily

# Restrict access to cron weekly
- name: Restrict access to cron weekly
  command: chown root:root /etc/cron.weekly && chmod og-rwx /etc/cron.weekly

# Restrict access to cron monthly
- name: Restrict access to cron monthly
  command: chown root:root /etc/cron.monthly && chmod og-rwx /etc/cron.monthly

# Restrict access to cron d
- name: Restrict access to cron d
  command: chown root:root /etc/cron.d && chmod og-rwx /etc/cron.d

# Restrict access to ssh d
- name: Restrict access to ssh d
  command: chown root:root /etc/ssh/sshd_config && chmod 600 /etc/ssh/sshd_config

# Restrict access to logs
- name: Restrict access to logs
  command:  chmod -R g- wx,o-rwx /var/log/*


- name: Limit MaxAuthTries to 4 #MaxAuthTries 6 -> MaxAuthTries 4
  replace:
    path: /etc/ssh/sshd_config
    regexp: '(\s+)MaxAuthTries(\s+.*)?$'
    replace: 'MaxAuthTries 4'
    backup: yes

- name: Set SSH timeout in conf
  lineinfile:
    path: /etc/ssh/sshd_config
    line: {{ item }}
    create: yes
    with_items:
      - ClientAliveInterval 300
      - ClientAliveCountMax 0
      -  LogLevel INFO
      - IgnoreRhosts yes
      - HostbasedAuthentication no
      - PermitUserEnvironment no

...
