---

- name: Playbook to set DNS entry for loadbalancer
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Get informations about Hostingbase Cloudformation Stack
      cloudformation_info:
        stack_name: hostingbase
        stack_resources: yes
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
        region: "{{ region }}"
      register: cloudformation_output

    - name: Get informations about application loadbalancer
      elb_application_lb_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        load_balancer_arns:
          - "{{ cloudformation_output.cloudformation['hostingbase'].stack_resources['elb'] }}"
      register: elb_application_output

    - name: Get informations about network loadbalancer
      elb_application_lb_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        load_balancer_arns:
          - "{{ cloudformation_output.cloudformation['hostingbase'].stack_resources['elbSSH'] }}"
      register: elb_network_output

    - name: set dns variable
      set_fact:
        dns_network: "{{ elb_network_output.load_balancers[0].dns_name }}"
        dns_application: "{{ elb_application_output.load_balancers[0].dns_name }}"


    - name: debug
      debug: msg="{{ dns_network }} && {{ dns_application }}"

    - name: set application dns on cloudflare
      cloudflare_dns:
        zone: it-economics-testing.de
        record: loadbalancer-testing.aws
        type: CNAME
        value: "{{ dns_application }}"
        ttl: 1
        account_email: "{{ account_email }}"
        api_token: "{{ api_token }}"
        state: present

    - name: set network dns on cloudflare
      cloudflare_dns:
        zone: it-economics-testing.de
        record: ssh.aws
        type: CNAME
        value: "{{ dns_network }}"
        ttl: 1
        account_email: "{{ account_email }}"
        api_token: "{{ api_token }}"
        state: present

...
