- hosts: amibuilder

  vars:
    built_at: "{{ ansible_date_time.iso8601 }}"
    built_at_epoch: "{{ ansible_date_time.epoch }}"

  tasks:

  - name: bundle ami
    ec2_ami:
      instance_id: "{{ ami_instance.tagged_instances.0.id }}"
      region: "{{ region }}"
      state: present
      description: This was provisioned {{ built_at }}
      name: atlassian-{{ built_at_epoch }}
      wait: no
      wait_timeout: 2700
      tags:
        Name: "itergo-application-{{ ansible_date_time.iso8601 }}"
        State: "{{ build_state }}"
        Customer: "itergo"
    register: amioutput

  - name: output new ami info
    debug: msg="AMI ID {{ amioutput.image_id }} \n Built at {{ built_at }}"

#  - name: gather facts about an AMI using ami-id
#    ec2_ami_facts:
#      region: "eu-central-1"
#      image_ids: "{{ amioutput.image_id }}"
##    register: amifacts
  #  until: amifacts.images[0].state == 'available'
  #  retries: 60
  #  delay: 60

#  - debug: msg="{{ amifacts.images[0].state }}"

  - name: Wait 30 Minutes as AWS is stupid sometimes
    pause: seconds=1800

  - name: share ami with it-e account for use in environments/testing
    shell: aws ec2 --region {{ region }} modify-image-attribute --image-id {{ amioutput.image_id }} --launch-permission "{\"Add\":[{\"UserId\":\"{{ item }}\"}]}"
    with_items: "{{ shared_with }}"
  
  - name: share ami with MS Teams
    shell:
      cmd: |
        curl -H 'Content-Type: application/json' -d "{'text': 'New itergo AMI: {{ amioutput.image_id }}'}" https://asmoubbm.webhook.office.com/webhookb2/f7d73b3c-1b8b-4fad-a52a-e6174f322fd5@41567caa-2f7d-4d52-8ed3-eb6b36fd70dd/IncomingWebhook/e3d25ef9e7364275a6b06e52a33956f9/289fb03e-2930-4d20-aa8b-ec036e73e905

#- hosts: localhost
#  remote_user: ubuntu
#  become: false
#  tasks:

#  - name: Wait for server to come back after bundle
#    wait_for: host={{ groups['atlassian-application'][0] }} state=started port=22 timeout=300 search_regex=OpenSSH

    # only needed because installation is too fast
  - name: Wait until instance is ready to be bundled
    pause: seconds=90
