- hosts: amibuilder

  tasks:
  - name: Get instance id
    ec2_instance_info:
      region: "{{ region }}"
      filters:
        "tag:role": temporary_instance
    register: info_instances

  - name: Show instance id
    debug: msg="{{ info_instances.instances.0.instance_id }}"

  - name: Terminate temporary instance
    ec2:
      region: "{{ region }}"
      state: 'absent'
      instance_ids: '{{ info_instances.instances.0.instance_id}}'
