---
  - name: Playbook for Cloudformation Stack deleteion
    hosts: localhost
    gather_facts: no

    tasks:
      - name: Get information about Cloudformation Stack
        cloudformation_info:
          stack_name: itergotest
          stack_resources: yes
          region: "{{ region }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          security_token: "{{ security_token }}"
        ignore_errors: yes
        register: cloudformation_base_output

      - name: Delete itergotest
        block:
          - name: Set Vars
            set_fact:
              logBucket: "{{ cloudformation_base_output.cloudformation['itergotest'].stack_resources['logBucket'] }}"
              backupBucket: "{{ cloudformation_base_output.cloudformation['itergotest'].stack_resources['backupBucket'] }}"
              efsFilesystem: "{{ cloudformation_base_output.cloudformation['itergotest'].stack_resources['FileSystemResource'] }}"

          - name: Delete itergotest cloudformation
            cloudformation:
              stack_name: "itergotest"
              state: "absent"
              aws_access_key: "{{ aws_access_key }}"
              aws_secret_key: "{{ aws_secret_key }}"
              security_token: "{{ security_token }}"
              region: "{{ region }}"

          - name: Delete itergotest s3 logBucket
            s3_bucket:
              region: "{{ region }}"
              name: "{{ logBucket }}"
              state: absent
              force: yes
              aws_access_key: "{{ aws_access_key }}"
              aws_secret_key: "{{ aws_secret_key }}"
              security_token: "{{ security_token }}"

          - name: Delete itergotest s3 backupBucket
            s3_bucket:
              region: "{{ region }}"
              name: "{{ backupBucket }}"
              state: absent
              force: yes
              aws_access_key: "{{ aws_access_key }}"
              aws_secret_key: "{{ aws_secret_key }}"
              security_token: "{{ security_token }}"

          - name: Delete itergotest efsFilesystem
            efs:
              region: "{{ region }}"
              id: "{{ efsFilesystem }}"
              state: absent
              aws_access_key: "{{ aws_access_key }}"
              aws_secret_key: "{{ aws_secret_key }}"
              security_token: "{{ security_token }}"
        when: cloudformation_base_output is defined
