- name: Install required software
  hosts: atlassian-application
  remote_user: ubuntu
  become: yes

  roles:
    - update-all-packages
    - awscli
    - docker_host
    - awsmon
    - awslogs_cloudwatch
    - awsefs
    - swapfile
    - atlassian_aws
    - sophos_download
    - ntpd
    - unattended-upgrades
    - authorized_keys

  tasks:
    - name: Ensure dependencies are installed
      apt:
        state: present 
        update_cache: yes
        pkg:
        - parted
        - postgresql-client
        - xmlstarlet
        - gzip
        - openssl

    - name: Pre download images
      command: docker pull {{ item }}
      with_items:
        - "docker.it-economics.de/proxy/iteconomics/confluence:itergo-prod"
        - "docker.it-economics.de/proxy/iteconomics/jira:itergo-prod"
        - "docker.it-economics.de/proxy/iteconomics/confluence:itergo-testing"
        - "docker.it-economics.de/proxy/iteconomics/jira:itergo-testing"
        - "docker.it-economics.de/proxy/iteconomics/duply:latest"
        - "docker.it-economics.de/proxy/library/postgres:{{ postgres_version }}"

    - name: Wait until instance is ready to be bundled
      pause: seconds=90
