---
- name: Test Playbook Application
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Get informations about Itergo Cloudformation Stack
      cloudformation_info:
        stack_name: itergotest
        stack_resources: yes
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
        region: "{{ region }}"
      register: cloudformation_output

    - name: Set Vars
      set_fact:
        database: "{{ cloudformation_output.cloudformation['itergotest'].stack_outputs['dataBaseEndpoint'] }}"

    - name: Test Setup or Update of {{ application }}
      include_role:
        name: run-test
