---

applications:
  test-stack:
    jira-test:
      name: "{{ jiraabn.app }}-{{ jiraabn.stage }}_db"
      image: "{{ POSTGRESIMAGE }}"
      restartPolicy: "{{ RESTARTPOLICY }}"
      volumes:
        - "/mnt/data/{{ jiraabn.stage }}/{{ jiraabn.app }}/data:{{ PGDATA }}:rw"
      environment:
        POSTGRES_USER: "{{ jiraabn.app }}-{{ jiraabn.stage }}"
        POSTGRES_DB: "{{ jiraabn.app }}-{{ jiraabn.stage }}"
        POSTGRES_PASSWORD: "{{ jiraabn.DATABASE_PASSWORD }}"
        PGDATA: "{{ PGDATA }}"
      ports:
        - "5432:5432"
      networks:
        - database
      labels:
        - "traefik.enable: false"
    confluence-test:
      name: "{{ confluenceabn.app }}-{{ confluenceabn.stage }}_db"
      image: "{{ POSTGRESIMAGE }}"
      restartPolicy: "{{ RESTARTPOLICY }}"
      volumes:
        - "/mnt/data/{{ confluenceabn.stage }}/{{ confluenceabn.app }}/data:{{ PGDATA }}:rw"
      environment:
        POSTGRES_USER: "{{ confluenceabn.app }}-{{ confluenceabn.stage }}"
        POSTGRES_DB: "{{ confluenceabn.app }}-{{ confluenceabn.stage }}"
        POSTGRES_PASSWORD: "{{ confluenceabn.DATABASE_PASSWORD }}"
        PGDATA: "{{ PGDATA }}"
      ports:
        - "5433:5432"
      networks:
        - database
      labels:
        - "traefik.enable: false"

  dev-stack:
    jira-test:
      name: "{{ jiradev.app }}-{{ jiradev.stage }}_db"
      image: "{{ POSTGRESIMAGE }}"
      restartPolicy: "{{ RESTARTPOLICY }}"
      volumes:
        - "/mnt/data/{{ jiradev.stage }}/{{ jiradev.app }}/data:{{ PGDATA }}:rw"
      environment:
        POSTGRES_USER: "{{ jiradev.app }}-{{ jiradev.stage }}"
        POSTGRES_DB: "{{ jiradev.app }}-{{ jiraabn.stage }}"
        POSTGRES_PASSWORD: "{{ jiradev.DATABASE_PASSWORD }}"
        PGDATA: "{{ PGDATA }}"
      ports:
        - "5434:5432"
      networks:
        - database
      labels:
        - "traefik.enable: false"
    confluence-test:
      name: "{{ confluencedev.app }}-{{ confluencedev.stage }}_db"
      image: "{{ POSTGRESIMAGE }}"
      restartPolicy: "{{ RESTARTPOLICY }}"
      volumes:
        - "/mnt/data/{{ confluencedev.stage }}/{{ confluencedev.app }}/data:{{ PGDATA }}:rw"
      environment:
        POSTGRES_USER: "{{ confluencedev.app }}-{{ confluencedev.stage }}"
        POSTGRES_DB: "{{ confluencedev.app }}-{{ confluencedev.stage }}"
        POSTGRES_PASSWORD: "{{ confluencedev.DATABASE_PASSWORD }}"
        PGDATA: "{{ PGDATA }}"
      ports:
        - "5435:5432"
      networks:
        - database
      labels:
        - "traefik.enable: false"
