---

- debug:
    msg: "{{ app }}"
  when: debug == true

- name: Create traefik network
  docker_network:
    name: "{{ traefik_network }}"
    state: present
  when: traefik_network is defined

- name: recreate or rollout services
  docker_compose:
    project_src: "{{ composerFilePath }}/{{ app.key }}"
    state: present
    build: no
    pull: yes
    recreate: always
  register: output
  when: remote == true

- name: recreate or rollout services
  docker_compose:
    project_src: "{{ composerFilePath }}/{{ app.key }}"
    state: present
    build: no
    pull: yes
    recreate: always
  register: output
  delegate_to: localhost
  when: remote != true

- debug:
    var: output
  when: debug == true

...
