---
- hosts: localhost

  tasks:
  - name: Send delete request to directory
    uri:
      method: POST
      return_content: yes
      headers: {"Authorization": "Basic {{ hostvars.get('localhost').get('auth_b64') }}" }
      url: "{{ hostvars.get('localhost').get('directory_url') }}{{ hostvars.get('localhost').get('directory_url_delete_user') }}?api_token={{ hostvars.get('localhost').get('admin_api_token') }}"
      body_format: json
      body:
        data: "{{ hostvars.get('localhost').get('username') }}"
    register: response
    failed_when: "'false' in response.json['Object Status'] or 'json' not in response"

  - uri:
      url: "{{ ticket_system }}/rest/api/2/issue/{{ hostvars.get('localhost').get('ticket_number') }}/comment"
      user: "{{ ticket_user }}"
      password: "{{ ticket_password }}"
      method: "POST"
      force_basic_auth: yes
      status_code: [201]
      body_format: "json"
      body:
        body: "Done with ldap"

  - name: inform jira about new user
    uri:
      url: "{{ ticket_system }}/rest/api/2/issue/{{ hostvars.get('localhost').get('ticket_number') }}/transitions"
      user: "{{ ticket_user }}"
      password: "{{ ticket_password }}"
      method: "POST"
      force_basic_auth: yes
      status_code: [204]
      body_format: "json"
      body:
        transition:
          id: "731"
