#!/usr/bin/env ansible-playbook
---

###
##
###

- name: Create Composefiles for Hosts
  hosts: docker_hosts
  become: true

  tasks:
   - name: "Deploy Traefik"
     include_role:
       name: docker_stack_traefik
     when: traefik_enabled is defined and traefik_enabled

#    - name: "Create Application-Config-Files"
#      include_role:
#        name: deploy_configs
#      with_dict: "{{ applications }}"
#      loop_control:
#        loop_var: stack

    - name: "Create Docker-Compose-Files"
      include_role:
        name: create_docker_compose
      with_dict: "{{ applications }}"
      loop_control:
        loop_var: app

    - name: "Deploy  Docker-Compose-Files"
      include_role:
        name: deploy_docker_compose
      with_dict: "{{ applications }}"
      loop_control:
        loop_var: app


...
