---
events-app-backend:
  DATABASE_HOSTNAME: "events-app-backend_db"
  DATABASE_PASSWORD: "42+y)m(9MFa4QP"
  DATABASE_USER: "events-app"
  DATABASE_DB: "iteevents"

skillmatrix-service:
  POSTGRESQL_URL: "jdbc:postgresql://hre1vrt7i07k54.cmeuro3rr38y.eu-central-1.rds.amazonaws.com:5432/mindmapdb"
  POSTGRESQL_USER: "mindmap"
  POSTGRESQL_PASSWORD: "pcqfJDMmDW7W_N4fjDUe22HK922YLDr"
  STATIC_CONTENT_PATH: /usr/share/nginx/html

atlassian-quote:
  OpenID_ClientSecret: 'ckdIg/mzxvH0vbb15xZ/tO5TJzHc+khWxLTtxMzdHYY='
  OpenID_ClientID:     'a2543f80-c71f-4c0e-b2b1-9e5081542bc6'
  OpenID_MetaDataURL:  'https://login.microsoftonline.com/41567caa-2f7d-4d52-8ed3-eb6b36fd70dd/v2.0/.well-known/openid-configuration'
  OpenID_RedirectURL:  'https://atlassian-quote.it-economics.de/redirect_uri/'
  OpenID_Mailpost:     '@it-economics.de'
  LDAP_Host:           "ldap://ldap01:389/ou=people,dc=it-economics,dc=de?uid??(objectclass=*)"
  LDAP_Group:          'cn=vs_atlassian,ou=groups,dc=it-economics,dc=de'

memorysourceexport:
  AUTH_USERS_JSON: '{ "vCardUser": "TAwW97z3QJKj8DRMVNT4&v*fISz2X$iH8@lcqYKHlN" }'

limesurvey:
  DB_HOST: "ite-mariadb.cmeuro3rr38y.eu-central-1.rds.amazonaws.com"
  DB_NAME: limesurvey
  DB_USER: limesurvey
  DB_PASS: "{{ limesurvey_db_pass }}"
  LIMESURVEY_TITLE: "it-economics Surveys"
  LIMESURVEY_ADMIN: ite-admin
  LIMESURVEY_ADMIN_PASS: "{{ limesurvey_admin_pass }}"
  LIMESURVEY_ADMIN_NAME: Sysadmin
  LIMESURVEY_ADMIN_MAIL: "{{ sysadmin_mail }}"
  LIMESURVEY_DEFAULT_LANG: de
  LIMESURVEY_SHOW_SCRIPT_NAME: 'true'
  LDAP_SERVER: "{{ ldap_url }}"
  LDAP_PORT: '20636'
  LDAP_TLS: '1'
  LDAP_ALLOW_CREATION_TO_LOGGEDIN: '1'
  LDAP_GROUP_NAME: survey_user
  LDAP_USER_PREFIX: 'uid='
  LDAP_USER_SUFFIX: ',ou=people,dc=it-economics,dc=de'
  LDAP_USER_SEARCH_BASE: 'ou=people,dc=it-economics,dc=de'
  LDAP_GROUP_SEARCH_BASE: 'ou=groups,dc=it-economics,dc=de'
  LDAP_BIND_DN: "{{ ldap_directory_user }}"
  LDAP_BIND_PASS: "{{ ldap_directory_pass }}"
  LIMESURVEY_DEBUG: '0'
  ADMIN_THEME_NAME: iteconomics
  DEFAULT_TEMPLATE: iteconomics
...
