---

- hosts: amibuilder

  tasks:
  - name: Ensure python3 is installed
    apt:
      name: python3-pip
      update_cache: yes
      state: present
    become: yes

  - name: Ensure boto is installed
    pip:
      name: boto
      state: present
    become: yes

  - name: Ensure boto3 is installed
    pip:
      name: boto3
      state: present
    become: yes

  - name: Ensure awscli is installed
    pip:
      name: awscli
      state: present
    become: yes

  - name: Find all ubuntu 20.04 amis
    ec2_ami_info:
      region: "{{ region }}"
      owners: "099720109477"
      filters:
        name: "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server*"
    register: amis

  - name: launch temporary instance
    vars:
      ubuntu_ami: >
        {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}
    ec2:
      assign_public_ip: yes
      region: "{{ region }}"
      key_name: "{{ key_name }}"
      group_id: "{{ group_id }}"
      instance_type: m5.4xlarge
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      image: "{{ ubuntu_ami.image_id }}"
      wait: yes
      wait_timeout: 500
      exact_count: 1
      count_tag:
         role: temporary_instance
      instance_tags:
         role: temporary_instance
         Name: "hostingbuild-{{ ansible_date_time.iso8601 }}"
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 50
          delete_on_termination: true
    register: ami_instance

  - name: Wait 5 Minutes as AWS is slow sometimes
    pause:
      seconds: 300

  - name: add host to group
    add_host:
      name: "{{ ami_instance.tagged_instances.0.public_ip }}"
      groups: atlassian_application
      ansible_python_interpreter: /usr/bin/python3

...
