- name: Install required software
  hosts: atlassian_application
  remote_user: ubuntu
  become: yes

  roles:
    - update-all-packages
    - awscli
    - docker_host
    - awsmon
    - awslogs_cloudwatch
    - awsefs
    - swapfile
    - atlassian_aws
    - sophos_download
    - unattended-upgrades
    - ntpd
    - authorized_keys

  tasks:
    - name: Ensure dependencies are installed
      apt:
        state: present
        update_cache: yes
        pkg:
        - parted
        - postgresql-client
        - xmlstarlet
        - gzip
        - openssl

    - name: Pre download images
      command: docker pull {{ item }}
      with_items:
        - "docker.it-economics.de/proxy/iteconomics/confluence:hosting" #confluence managed hosting
        - "docker.it-economics.de/proxy/iteconomics/confluence:latest" #confluence it-e
        - "docker.it-economics.de/proxy/iteconomics/confluence:testing" #confluence it-e
        - "docker.it-economics.de/proxy/iteconomics/jira:hosting" #jira managed hosting
        - "docker.it-economics.de/proxy/iteconomics/jira:latest" #jira it-e
        - "docker.it-economics.de/proxy/iteconomics/jira:testing" #jira it-e
        - "docker.it-economics.de/proxy/iteconomics/bitbucket:hosting" # bitbucket managed hosting
        - "docker.it-economics.de/proxy/iteconomics/bitbucket:latest" #bitbucket it-e
        - "docker.it-economics.de/proxy/iteconomics/bitbucket:testing" #bitbucket it-e
        - "docker.it-economics.de/proxy/library/postgres:{{ postgres_version }}"
    - name: Wait until instance is ready to be bundled
      pause:
        seconds: 90
