---

- name: Generate cfg2html output
  hosts: atlassian_application
  become: yes
  roles:
    - { role: cfg2html, tag: "{{ hostvars['amibuilder']['amioutput']['image_id']|default('hostname') }}" }

- name: Output details
  hosts: amibuilder
  become: false
  tasks:
    - name: Output new AMI information
      debug:
        msg: "AMI ID {{ amioutput.image_id }}"

    - name: Shared with
      debug:
        msg: "AMI shared with {{ shared_with|join(',') }}"

    - name: Ensure target dir exsists
      local_action: file path=target state=directory

    - name: Create release bundle
      local_action: template src=templates/hosting/info.j2 dest=target/info.txt

    - name: Create release bundle
      local_action: copy src=output/{{ amioutput.image_id }}.html dest=target/cfg2html.html

...
