---

- name: Rollout Playbook Hosting Application
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Get informations about Hostingbase Cloudformation Stack
      cloudformation_info:
        stack_name: hostingbase
        stack_resources: yes
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
        region: "{{ region }}"
      register: cloudformation_output

    - name: Set Vars
      set_fact:
        database:         "{{ cloudformation_output.cloudformation['hostingbase'].stack_outputs['dataBaseEndpoint'] }}"
        securityGroupId:  "{{ cloudformation_output.cloudformation['hostingbase'].stack_outputs['SecurityGroupWebApp'] }}"
        lambda_name:      "{{ cloudformation_output.cloudformation['hostingbase'].stack_resources['rdsCreateLambda'] }}"
        efsFileSystemID:  "{{ cloudformation_output.cloudformation['hostingbase'].stack_resources['FileSystemResource'] }}"
        stackname:        "{{ customer }}-{{ hosting_application }}"

    - name: Update {{ hosting_application }} Cloudformation
      include_role:
        name: run-hosting
      vars:
        app: "{{ application }}"

    - name: Get informations about {{ hosting_application }} Cloudformation Stack
      cloudformation_info:
        stack_name: "{{ customer }}-{{ hosting_application }}"
        stack_resources: yes
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
        region: "{{ region }}"
      register: cloudformation_output

    - name: Remove suspended processes from autoscaling group
      ec2_asg:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        name: "{{ cloudformation_output.cloudformation[vars['stackname']].stack_resources['ApplicationAsg'] }}"
        suspend_processes: []
        state: "present"
        default_cooldown: 150
        health_check_period: 900
        lc_check: "no"
        metrics_collection: "yes"


    - name: Get informations about autoscaling group
      ec2_asg_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        name: "{{ cloudformation_output.cloudformation[vars['stackname']].stack_resources['ApplicationAsg'] }}"
      register: asg_output
      failed_when: "{{ asg_output.results | length == 0 }}"

    - name: debug
      debug:
        msg: "{{ asg_output.results[0].instances[0].instance_id }}"


    - name: Terminate instance to perform update
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        security_token: "{{ security_token }}"
        region: "{{ region }}"
        state: 'absent'
        instance_ids: '{{ asg_output.results[0].instances[0].instance_id }}'

...
