---

applications:
  bamboo_stack:
    bamboo:
      name: bamboo
      image: "{{ docker_registry }}iteconomics/bamboo:latest"
      restartPolicy: always
      volumes:
        - "{{ docker_home }}/bamboo/data:/var/atlassian/application-data/bamboo"
        - "{{ docker_home }}/bamboo/config/server.xml:/opt/atlassian/bamboo/conf/server.xml"

      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.bamboo.loadbalancer.server.port: '8085'"
        - "traefik.http.routers.bamboo_http.rule: 'Host(`bamboo.it-economics.de`)'"
        - "traefik.http.routers.bamboo_http.entrypoints: 'web'"
        - "traefik.http.routers.bamboo_http.middlewares: 'forcehttps@file'"
        - "traefik.http.routers.bamboo.rule: 'Host(`bamboo.it-economics.de`)'"
        - "traefik.http.routers.bamboo.entrypoints: 'websecure'"
        - "traefik.http.routers.bamboo.tls: 'true'"
        - "traefik.http.routers.bamboo.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.bamboo.tls.domains[0].main: 'it-economics.de'"
        - "traefik.http.routers.bamboo.tls.domains[0].sans: '*.it-economics.de'"
      networks:
        - "backbone"
      ports:
        - "54663:54663"

...
