#!/usr/bin/env ansible-playbook
---

###
## Licenced under CC-BY
##
###
- hosts: updatableServers
  serial: 1

  tasks:

    - name: 'update Server'
      include_role:
        name: update_server

...
