---

- name: install the latest version of basic toolset
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default( package_state) }}"
  with_items: "{{ install_tools }}"

- name: install pip packages, force upgrade
  pip:
    name: "{{ item }}"
    executable: pip3
    state: latest
  with_items:
    - pip
    # - python3-keyczar
    # - ansible

- name: update certificate chain
  command: update-ca-certificates

...
