---

# the basic toolset within roles default variables can be extended by the
# usage of the variable `additional_basic_tools` on host or group level.
- name: 'merge tools to be installed'
  set_fact:
    install_tools: "{{ basic_toolset + additional_basic_tools | default([]) }}"

- name: install the latest version of basic toolset
  package:
    name: "{{ item.name }}"
    state: "{{ item.state | default( package_state) }}"
  with_items: "{{ install_tools }}"

- name: install pip packages, force upgrade
  pip:
    name: "{{ item }}"
    executable: pip3
    state: latest
  with_items:
    - pip
    # - python3-keyczar
    # - ansible

- name: update certificate chain
  command: update-ca-certificates

- name: install configs for unattended upgrades
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
  with_items:
    - 10periodic
    - 50unattended-upgrades

...
