---

- name: install the latest version of basic toolset
  package:
    name:
      - locales
      - xmlstarlet
      - python3
      - python3-yaml
      - python3-jinja2
      - python3-httplib2
      - python3-paramiko
      - python3-setuptools
      - python3-pkg-resources
      - python3-pip
      - htop
      - tree
      - nano
      - vim
      - wget
      - curl
      - software-properties-common
      - libcurl4-gnutls-dev
      - libexpat1-dev
      - gettext
      - libz-dev
      - libssl-dev
      - build-essential
      - autoconf
      - git
      - awscli
      - zip
      - unzip
    state: latest

- name: install pip packages, force upgrade
  pip:
    name: "{{ item }}"
    executable: pip3
    state: latest
  with_items:
    - pip
    # - python3-keyczar
    # - ansible

- name: get current it-e CA
  get_url:
    url: http://ca.it-economics.de/it-economics_CA.crt
    dest: /usr/share/ca-certificates/it-economics_CA.crt
    mode: '0755'

# add it-e CA only to config if it is not already present
- name: update certificate chain
  shell: cat /etc/ca-certificates.conf | grep -E ^it-economics_CA\.crt$ > /dev/null; if ! [ $? -eq 0 ]; then echo "it-economics_CA.crt" >> /etc/ca-certificates.conf; fi; update-ca-certificates

...
