#!/usr/bin/env ansible-playbook
---

###
## Licenced under CC-BY
##
###
- hosts: 'all:!localhost'
  become: yes

  tasks:

    - name: 'configure basic firewall'
      include_role:
        name: firewall

...
