---
- hosts: localhost

  tasks:
  - name: Check if user exists
    command: >
      ldapsearch -x
      -D "uid={{ hostvars.get('localhost').get('admin_user') }},ou=people,dc=it-economics,dc=de"
      -w {{ hostvars.get('localhost').get('admin_password') }}
      -H {{ hostvars.get('localhost').get('ldap_url') }}
      -b uid={{ hostvars.get('localhost').get('username') }},ou=people,dc=it-economics,dc=de
    register: user_exists
    ignore_errors: true
    no_log: "{{ no_log|default('true') }}"

  - name: Delete user from groups even if user has already been deleted
    include: ldap_groups.yml

  - name: Delete user
    include: ldap_user.yml
    when: user_exists is success
