---
# TODO Add default values for ticket_system & ldap_url
- hosts: localhost
  become: true
  vars:
    env: testing
    mail:
      - "it-economics.bg"
      - "it-economics.de"
      - "it-economics.ch"
      - "it-economics.com"

  tasks:
    - debug:
        msg: "{{ office_2fa_method }}"

    - name: 'Ask for User 2FA'
      pause:
        prompt: "Please enter your 2FA for Office (long running if possible!)"
      register: office_2fa_code_input
      when: ( office_2fa_method == "Code" )

    - name: 'Define our used variable office_2fa_code'
      set_fact:
        office_2fa_code: "{{ office_2fa_code_input.user_input }}"
      when: office_2fa_method == "Code"

    - debug:
        msg: "{{ office_2fa_code }}"

    - block:
      - name: Start selenium container
        docker_container:
          name: selenium_office
          image: selenium/standalone-firefox:83.0
          volumes:
            - "/dev/shm:/dev/shm"
          ports:
            - "4446:4444"
            - "5902:5900"

      - name: Copy generation script
        copy: src=../files/office.py dest=/tmp/office.py mode=755

      - name: Remove 2fa and set password for offlineimap
        shell: /tmp/office.py -u {{ hostvars.get('localhost').get('email') }} -up {{ hostvars.get('localhost').get('email_password')| quote }} -m {{ hostvars.get('localhost').get('office_2fa_method') }} -c {{ hostvars.get('localhost').get('office_2fa_code') }} -au {{ hostvars.get('localhost').get('office_user') }} -ap {{ hostvars.get('localhost').get('office_password')| quote }}


      - name: Remove selenium container
        docker_container:
          name: selenium_office
          state: absent
      when: hostvars.get('localhost').get('email').split("@")[1] in mail
      ignore_errors: yes
