- hosts: localhost
  become: false
  vars:
    noSSL:
      - "12700"
      - "11403"
      - "11402"
  tasks:
    # Deploy CRT to LDAP
    - block:
      - name: Create temporary file
        command: mktemp
        register: tempFile

      - name: Get contents of pem file and remove header and footer
        shell: awk '/-----BEGIN CERTIFICATE-----/{flag=1;next}/-----END CERTIFICATE-----/{flag=0}flag' /tmp/it-economics_{{ user.registration.user.mail }}.crt | sed -e 's/^/ /'
        register: certificate

      - name: Setting Facts for Cert
        set_fact:
          tempFile: "{{ tempFile.stdout }}"
          certificate: "{{ certificate.stdout }}"

      - name: Copy template to tmp location
        template: src=../templates/certificate.ldif.j2 dest="{{ tempFile }}.ldif"

      - name: Import ldif file
        command: >
          ldapmodify -x
          -D "uid={{ admin_user }},ou=people,dc=it-economics,dc=de"
          -w "{{ admin_password }}"
          -H "{{ ldap_url }}"
          -f "{{ tempFile }}.ldif"
        no_log: "{{ no_log|default('true') }}"

      - name: Ensure ldif file is removed
        file: path={{ tempFile }}.ldif state=absent
      when: user.registration.contract.employerId not in noSSL
