---

docker_host: true

applications:
  appstore_stack:
    appstore:
      name: appstore
      image: iteconomics/apache:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/appstore/web/certs:/certs"
        - "/mnt/shared/applications/appstore/web/config:/etc/apache2/sites-enabled"
        - "/mnt/shared/applications/appstore/data:/var/www/html"
      labels:
        - "traefik.backend=appstore"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:appstore.it-economics.de"
        - "traefik.port=80"
        - "traefik.protocol=http"
      environment:
        MODS: "ssl ldap authnz_ldap php7.0 rewrite headers"
      network_mode: proxy

    appstore_ssh:
      name: appstore_ssh
      image: felixkazuyade/worksuite:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/appstore/ssh/authorized_keys:/root/.ssh/authorized_keys"
        - "/mnt/shared/applications/appstore/data:/var/www/html"
      labels:
        - "traefik.enable=false"
      ports:
      - "50022:22"

  atlassian-quote_stack:
    atlassian-quote:
      name: atlassian-quote
      image: iteconomics/atlassian-quote:latest
      restartPolicy: always
      labels:
        - "traefik.backend=Atlassian Quote Tool"
        - "traefik.frontend.rule=Host:atlassian-quote.it-economics.de"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.docker.network={{ traefik_network }}"
        - "traefik.port=80"
        - "traefik.protocol=http2"
      environment:
        OpenID_ClientSecret: 'ckdIg/mzxvH0vbb15xZ/tO5TJzHc+khWxLTtxMzdHYY='
        OpenID_ClientID:     'a2543f80-c71f-4c0e-b2b1-9e5081542bc6'
        OpenID_MetaDataURL:  'https://login.microsoftonline.com/41567caa-2f7d-4d52-8ed3-eb6b36fd70dd/v2.0/.well-known/openid-configuration'
        OpenID_RedirectURL:  'https://atlassian-quote.it-economics.de/redirect_uri/'
        OpenID_Mailpost:     '@it-economics.de'
        LDAP_Host:           "{{ ldap_url }}"
        LDAP_Group:          'cn=vs_atlassian,ou=groups,dc=it-economics,dc=de'
        LDAP_BindDN:         "{{ ldap_directory_user }}"
        LDAP_BindPassword:   "{{ ldap_directory_pass }}"
      network_mode: proxy


  crowd_stack:
    crowd:
      name: crowd
      image: iteconomics/crowd:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/crowd/conf/server.xml:/opt/atlassian/crowd/apache-tomcat/conf/server.xml"
        - "/mnt/shared/applications/crowd/data:/var/atlassian/application-data/crowd"
      labels:
        - "traefik.backend=crowd"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:crowd.it-economics.de"
        - "traefik.port=8095"
        - "traefik.protocol=http"
      network_mode: proxy

  directory-guest_stack:
    directory-guest:
      name: directory-guest
      image: iteconomics/directory:latest
      restartPolicy: always
      volumes:
      - "/mnt/shared/applications/certs/data/data:/var/www/html/storage/app/certs"
      - "/mnt/shared/applications/certs/data/templates:/var/www/html/storage/app/templates"
      - "/mnt/shared/applications/directory-test/config/.env:/var/www/html/.env"
      - "/mnt/shared/applications/directory-test/database.sqlite:/var/www/html/database/database.sqlite"
      labels:
        - "traefik.backend=directory-guest"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:directory-guest.it-economics.de"
        - "traefik.port=80"
        - "traefik.protocol=http"
      environment:
        MODS: "ssl ldap authnz_ldap php7.0 rewrite headers"
      network_mode: proxy

  directory-test_stack:
    directory-test:
      name: directory-test
      image: iteconomics/directory:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/directory-guest/config/.env:/var/www/html/.env"
        - "/mnt/shared/applications/directory-guest/database.sqlite:/var/www/html/database/database.sqlite"
      labels:
        - "traefik.backend=directory-test"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:directory-test.it-economics.de"
        - "traefik.port=80"
        - "traefik.protocol=http"
      environment:
        MODS: "ssl ldap authnz_ldap php7.0 rewrite headers"
      network_mode: proxy

  directory_stack:
    directory:
      name: directory
      image: iteconomics/directory:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/directory/config/.env:/var/www/html/.env"
        - "/mnt/shared/applications/directory/database.sqlite:/var/www/html/database/database.sqlite"
        - "/mnt/shared/applications/certs/data/data:/var/www/html/storage/app/certs"
        - "/mnt/shared/applications/certs/data/templates:/var/www/html/storage/app/templates"
        - "/mnt/shared/applications/directory/cronjobs:/etc/cron.d/docker"
      labels:
        - "traefik.backend=directory"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:directory.it-economics.de"
        - "traefik.port=80"
        - "traefik.protocol=http"
      environment:
        START_CRON: 1
        MODS: "ssl ldap authnz_ldap php7.0 rewrite headers"
      network_mode: proxy

  teamsurvey-dashboard_stack:
    teamsurvey-dashboard:
      name: teamsurvey-dashboard
      image: iteconomics/teamsurvey-dashboard:latest
      restartPolicy: always
      labels:
        traefik.backend: "Teamsurvey Dashboard"
        traefik.frontend.rule: "Host:teamsurvey.it-economics.de"
        traefik.frontend.entryPoints: http,https
        traefik.port: "80"
        traefik.protocol: http
      environment:
        GRAPHQL_ENDPOINT: "https://teamsurvey-api.it-economics.de/graphql"
      network_mode: proxy

  vcard_stack:
    vcard:
      name: vcard
      image: iteconomics/apache:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/vcard/data:/data"
      labels:
        - "traefik.backend?it-e vcard server"
        - "traefik.frontend.rule=Host:vcard.it-economics.de"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.port=80"
        - "traefik.protocol=http"
      environment:
        MODS: "proxy proxy_http auth_basic authnz_ldap authz_core rewrite headers"
      network_mode: proxy

    vcardserver:
      name: vcardserver
      image: tomsquest/docker-radicale:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/vcard/config:/config"
        - "/mnt/shared/applications/vcard/data:/data"
      labels:
        - "traefik.enable=false"

    vcardsync:
      name: vcardsync
      image: iteconomics/contactsync_ldap_exporter:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/vcard/data:/data"
      labels:
        - "traefik.enable=false"
      environment:
        ITE_CONTACT_DIR: '/data/collections/collection-root/'
        ITE.EXPORTCONTACTDIR: '/data/collections/collection-root/'
        LDAP_PASSWORD: "{{ ldap_directory_pass }}"
        LDAP_URL: "{{ ldap_url }}"
        LDAP_USERNAME: "{{ ldap_directory_user }}"
        network_mode: proxy

  surveyappproxy_stack:
    surveyappproxy:
      name: surveyappproxy
      image: nginx:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/teamsurveyrest.it-economics.de/nginx.conf:/etc/nginx/nginx.conf"
      labels:
        - "traefik.backend=surveyappproxy"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:teamsurveyrest.it-economics.de"
        - "traefik.port=80"
        - "traefik.protocol=http"
      environment:
        MODS: "ssl ldap authnz_ldap php7.0 rewrite headers"
      network_mode: proxy

  share_stack:
    share:
      name: share
      image: nextcloud:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/share/data/apps:/var/www/html/apps"
        - "/mnt/shared/applications/share/data/config:/var/www/html/config"
        - "/mnt/shared/applications/share/data/data:/var/www/html/data"
      labels:
        - "traefik.backend=share.it-economics.de"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:share.it-economics.de"
        - "traefik.port=80"
        - "traefik.protocol=http"
      network_mode: proxy

  share-secrets_stack:
    share-secrets:
      name: share-secrets
      image: iteconomics/apache:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/share-secrets/apache/apache.j2:/templates/apache.j2"
        - "/mnt/shared/applications/share-secrets/html:/var/www/html/public"
      labels:
        - "traefik.backend=secrets.it-economics.de"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:secrets.it-economics.de"
        - "traefik.port=80"
        - "traefik.protocol=http"
      network_mode: proxy

  roominfo-service_stack:
    roominfo-service:
      name: roominfo-service
      image: iteconomics/icsviewer:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/roominfo-service/config/.env:/var/www/html/.env"
      labels:
        - "traefik.backend=roominfo-service.it-economics.de"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:roominfo-service.it-economics.de"
        - "traefik.port=80"
        - "traefik.protocol=http"
      network_mode: proxy

  portainer_stack:
    portainer:
      name: portainer
      image: portainer/portainer
      restartPolicy: always
      volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/mnt/shared/applications/portainer/data:/data'
      labels:
        - "traefik.backend=portainer.it-economics.de"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:portainer.it-economics.de"
        - "traefik.port=9000"
        - "traefik.protocol=http"
      network_mode: proxy

  phonestat_stack:
    phonestat:
      name: phonestat
      image: iteconomics/apache:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/phonestat/telefonstatus:/var/www/html"
      labels:
        - "traefik.backend=phonestat.it-economics.de"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:phonestat.it-economics.de"
        - "traefik.port=80"
        - "traefik.protocol=http"
      network_mode: proxy

  passcard_stack:
    passcard:
      name: passcard
      image: iteconomics/passcard:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/passcard/data:/var/www/html/storage"
      labels:
        - "traefik.backend=passcard.it-economics.de"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:passcard.it-economics.de"
        - "traefik.port=80"
        - "traefik.protocol=http"
      network_mode: proxy

  memorysourceexport_stack:
    memorysourceexport:
      name: memorysourceexport
      image: iteconomics/memorysourceexport:latest
      restartPolicy: always
      labels:
        - "traefik.backend=memory.it-economics.de"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:memory.it-economics.de"
        - "traefik.port=80"
        - "traefik.protocol=http"
      environment:
        LDAP_BindDN: "{{ ldap_directory_user }}"
        AUTH_USERS_JSON: '{ "vCardUser": "TAwW97z3QJKj8DRMVNT4&v*fISz2X$iH8@lcqYKHlN" }'
        LDAP_Host: "{{ ldap_url }}"
        LDAP_BASE_DN: "{{ ldap_base_dn }}"
        LDAP_BindPassword: "{{ ldap_directory_pass }}"
      network_mode: proxy

  ldap01_stack:
    ldap01:
      name: ldap01
      image: iteconomics/openldap:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/ldap01/data/certs:/certs"
        - "/mnt/shared/applications/ldap01/data/config:/etc/ldap/slapd.d"
        - "/mnt/shared/applications/ldap01/data/import:/import"
        - "/mnt/shared/applications/ldap01/data/data:/var/lib/ldap"
      labels:
        - "traefik.enable=false"
      ports:
        - "20636:636"

  ldap-guest_stack:
    ldap-guest:
      name: ldap-guest
      image: iteconomics/openldap:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/ldap-guest/data/certs:/certs"
        - "/mnt/shared/applications/ldap-guest/data/config:/etc/ldap/slapd.d"
        - "/mnt/shared/applications/ldap-guest/data/import:/import"
        - "/mnt/shared/applications/ldap-guest/data/data:/var/lib/ldap"
      labels:
        - "traefik.enable=false"
      ports:
      - "50022:22"

  ldap-test_stack:
    ldap-test:
      name: ldap-test
      image: iteconomics/openldap:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/ldap-test/data/certs:/certs"
        - "/mnt/shared/applications/ldap-test/data/config:/etc/ldap/slapd.d"
        - "/mnt/shared/applications/ldap-test/data/import:/import"
        - "/mnt/shared/applications/ldap-test/data/data:/var/lib/ldap"
      labels:
        - "traefik.enable=false"
      ports:
       - "636:636"

  ldap-certs_stack:
    ldap-certs:
      name: ldap-certs
      image: iteconomics/openldap:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/ldap-certs/data/certs:/certs"
        - "/mnt/shared/applications/ldap-certs/data/config:/etc/ldap/slapd.d"
        - "/mnt/shared/applications/ldap-certs/data/import:/import"
        - "/mnt/shared/applications/ldap-certs/data/data:/var/lib/ldap"
      labels:
        - "traefik.enable=false"
      ports:
        - "60636:636"

  kdc01_stack:
    kdc01:
      name: kdc01
      image:  docker.io/iteconomics/kdc:latest
      restartPolicy: always
      volumes:
        - "/dev/urandom:/dev/urandom"
        - "/mnt/shared/applications/kdc01/config:/kdc"
      labels:
        - "traefik.enable=false"
      ports:
        - "464:464/tcp"
        - "464:464/udp"
        - "749:749/tcp"
        - "749:749/udp"
        - "88:88/tcp"
        - "88:88/udp"

  limesurvey_stack:
    limesurvey:
      name: limesurvey
      image:  iteconomics/limesurvey:latest
      restartPolicy: always
      volumes:
        - "/mnt/shared/applications/survey/data/admin_theme:/var/www/html/upload/admintheme/iteconomics"
        - "/mnt/shared/applications/survey/data/template:/var/www/html/upload/themes/survey/iteconomics"
      labels:
        - "traefik.backend=survey"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:survey.it-economics.de"
        - "traefik.port=80"
        - "traefik.protocol=http"
      environment:
        DB_HOST: "ite-mariadb.cmeuro3rr38y.eu-central-1.rds.amazonaws.com"
        DB_NAME: limesurvey
        DB_USER: limesurvey
        DB_PASS: "{{ limesurvey_db_pass }}"
        LIMESURVEY_TITLE: "it-economics Surveys"
        LIMESURVEY_ADMIN: ite-admin
        LIMESURVEY_ADMIN_PASS: "{{ limesurvey_admin_pass }}"
        LIMESURVEY_ADMIN_NAME: Sysadmin
        LIMESURVEY_ADMIN_MAIL: "{{ sysadmin_mail }}"
        LIMESURVEY_DEFAULT_LANG: de
        LIMESURVEY_SHOW_SCRIPT_NAME: 'true'
        LDAP_SERVER: "{{ ldap_url }}"
        LDAP_PORT: '20636'
        LDAP_TLS: '1'
        LDAP_ALLOW_CREATION_TO_LOGGEDIN: '1'
        LDAP_GROUP_NAME: survey_user
        LDAP_USER_PREFIX: 'uid='
        LDAP_USER_SUFFIX: ',ou=people,dc=it-economics,dc=de'
        LDAP_USER_SEARCH_BASE: 'ou=people,dc=it-economics,dc=de'
        LDAP_GROUP_SEARCH_BASE: 'ou=groups,dc=it-economics,dc=de'
        LDAP_BIND_DN: "{{ ldap_directory_user }}"
        LDAP_BIND_PASS: "{{ ldap_directory_pass }}"
        LIMESURVEY_DEBUG: '0'
        ADMIN_THEME_NAME: iteconomics
        DEFAULT_TEMPLATE: iteconomics
      network_mode: proxy

composerFilePath: "/srv/docker-compose/"
remote: true

...

