---
applications:
  website_stack:
    wordpress:
      image: "{{ docker_registry }}iteconomics/wordpress:latest"
      name: website
      restartPolicy: always
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.routers.website_http.rule: 'Host(`www.it-economics.de`) || Host(`it-economics.de`)'"
        - "traefik.http.routers.website_http.entrypoints: 'web'"
        - "traefik.http.routers.website.rule: 'Host(`www.it-economics.de`) || Host(`it-economics.de`)'"
        - "traefik.http.routers.website.entrypoints: 'websecure'"
        - "traefik.http.routers.website.tls: 'true'"
        - "traefik.http.routers.website.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.website_http.middlewares: 'forcehttps@file'"
      environment:
        WORDPRESS_DB_HOST: "{{ websiteWordpress.WORDPRESS_DB_HOST }}"
        WORDPRESS_DB_NAME: "{{ websiteWordpress.WORDPRESS_DB_NAME }}"
        WORDPRESS_DB_USER: "{{ websiteWordpress.WORDPRESS_DB_USER }}"
        WORDPRESS_DB_PASSWORD: "{{ websiteWordpress.WORDPRESS_DB_PASSWORD }}"
        WORDPRESS_TABLE_PREFIX: "{{ websiteWordpress.WORDPRESS_TABLE_PREFIX }}"
#        WORDPRESS_DEBUG: "{{ websiteWordpress.WORDPRESS_DEBUG }}"
      volumes:
        - "/mnt/shared/applications/website/logs:/var/log/apache2"
        - "/mnt/shared/applications/website/wordpress/.htaccess:/var/www/html/.htaccess"
        - "/mnt/shared/applications/website/wordpress/assets:/var/www/html/assets"
        - "/mnt/shared/applications/website/wordpress/wp-content:/var/www/html/wp-content"
        - "/mnt/shared/applications/website/upload.ini:/usr/local/etc/php/conf.d/upload.ini"
      networks:
          backbone:
      # templates:
      #   htaccess:
      #     src: "custom/wordpress/htaccess.j2"
      #     dest: "/mnt/shared/applications/website/wordpress/.htaccess"
      #   uploadini:
      #     src: "custom/wordpress/upload.ini.j2"
      #     dest: "/mnt/shared/applications/website/upload.ini"

    ssh:
      name: worksuite
      image: "{{ docker_registry }}devopsansiblede/worksuite:latest"
      restartPolicy: always
      ports:
        - "222:22"
      environment:
        ROOT_PASSWORD: "{{ websiteSsh.ROOT_PASSWORD }}"
        UBUNTU_PASSWORD: "{{ websiteSsh.UBUNTU_PASSWORD }}"
        CRON: "{{ websiteSsh.CRON }}"
      volumes:
        - "/mnt/shared/applications/website/wordpress:/mnt/website"
        - "/mnt/shared/applications/website/ssh/authorized_keys:/root/.ssh/authorized_keys"
        - "/mnt/shared/applications/website/crontab:/var/spool/cron/crontabs"
        - "/mnt/shared/applications/website/www-data-id_rsa:/var/www/.ssh"
      labels:
        - "traefik.enable: 'false'"


  portainer_stack:
    portainer:
      image: "{{ docker_registry }}portainer/portainer-ce:latest"
      name: portainer
      restartPolicy: always
      labels:
        - "traefik.enable: 'true'"
        - "traefik.http.services.portainer.loadbalancer.server.port: '9000'"
        - "traefik.http.routers.portainer_http.rule: 'Host(`portainer-www.it-economics.de`)'"
        - "traefik.http.routers.portainer_http.entrypoints: 'web'"
        - "traefik.http.routers.portainer.rule: 'Host(`portainer-www.it-economics.de`)'"
        - "traefik.http.routers.portainer.entrypoints: 'websecure'"
        - "traefik.http.routers.portainer.tls: 'true'"
        - "traefik.http.routers.portainer.tls.certresolver: 'letsencrypt'"
        - "traefik.http.routers.portainer_http.middlewares: 'forcehttps@file'"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/mnt/shared/applications/portainer/data:/data"
      networks:
        backbone:

  portainer_agent_stack:
    portainer_agent:
      name: portainer_edge_agent
      image: "{{ docker_registry }}portainer/agent"
      restartPolicy: always
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/var/lib/docker/volumes:/var/lib/docker/volumes"
        - "/:/host"
        - "/mnt/shared/applications/portainer_agent_data/data:/data"
      labels:
        - "traefik.enable: false"
      environment:
        EDGE: 1
        EDGE_ID: 675a05d3-8c4f-4ab3-98c7-fa438692d59c
        EDGE_KEY: aHR0cDovL2RvY2tlcmhvc3QuYXdzLml0LWVjb25vbWljcy5kZTo5MDAwfGRvY2tlcmhvc3QuYXdzLml0LWVjb25vbWljcy5kZTo4MDAwfGQ3OjAxOjI5Ojg3OjYzOjY0OjA3OmY4OmJjOjhiOmI3OmNhOjY1OjRmOmM5OjQxfDc
        CAP_HOST_MANAGEMENT: 1
      networks:
        - "database"

...

