---

docker_host:      true
traefik_enabled:  true
remote:           true
docker_registry:  'docker.it-economics.de/proxy/'
composerFilePath: '/data/compose'
docker_home:      '/data/'

host_ufw_rules:

  # global_ufw_rules defined by firewall role
  # respects HTTP/S (80, 443 without protocol
  # restrictions) and SSH

  # allow any connection from office
  - rule: allow
    proto: "any"
    src: "212.114.221.222/32"

  # nagios
  - rule: allow
    port: "5666"
    proto: "any"

  # License-Server GasX
  - rule:  "allow"
    port:  "1099"
    proto: "any"
  - rule:  "allow"
    port:  "9998"
    proto: "any"
  - rule:  "allow"
    port:  "9999"
    proto: "any"

...
