---
alfresco:
  MYSQL_ROOT_PASSWORD: "tqi2KSxY3MXcuIqUGiOM"
  MYSQL_DATABASE: "alfresco"
  MYSQL_USER: "alfresco"
  MYSQL_PASSWORD: "AvQib3Rpyx65rl636Qsn"

socialpartner:
  MYSQL_ROOT_PASSWORD: "h7i8buZaZw4b9AoS77q1"
  MYSQL_DATABASE: "confluence"
  MYSQL_USER: "confluence"
  MYSQL_PASSWORD: "h7i8buZaZw4b9AoS77q1"

personiobackup:
  PERSONIOPASSWORD: 'askgDDfgasd342DF!34a'  
  PASSWORD: 'Admin12345!'

...
