#! /bin/bash
### BEGIN INIT INFO
# Provides: atlassian-application
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Atlassian application AWS init script
# Description: Atlassian application AWS init script
#
### END INIT INFO

function main {
  launch-config.sh $1 &
}

case "$1" in
 start)
   main "start"
   ;;
 stop)
   main "stop"
   ;;
 restart)
   main "stop"
   main "start"
   ;;
 *)
   echo "Usage: atlassian-application {start|stop|restart}" >&2
   exit 3
   ;;
esac
